avidemux_core/ADM_coreImage/src/ADM_imageSave.cpp
see http://avidemux.org/smuf/index.php?topic=12461.0
=> Don't try to delete ffmpeg codec

avidemux/cli/ADM_userInterfaces/ADM_gui2/gui_none.cpp
db99dbe added UI_reset declaration, but only a qt4 implementation
=> UI_reset needs to exist in CLI

avidemux_plugins/ADM_videoFilters6/telecide/Telecide_getFrame.cpp
http://avidemux.org/smif/index.php/topic,16901.0.html
=> Cast to int so we can take abs()

avidemux/common/ADM_editor/src/ADM_edSearch.cpp
see
http://avidemux.org/smif/index.php/topic,11557.msg60516.html#msg60516
http://avidemux.org/smif/index.php/topic,17173.0.html
=> Avoid crashing seeking for deleted keyframe

bootStrap.bash
This patch provides a simple option to modify install prefix without editing bootStrap.bash file. The default prefix /usr remains unchanged, both helper functions option_value() (literally stolen from MPlayer configure) and dir_check() could be reused for other purposes later.
=> [Build] Add --prefix=DIR option to bootStrap.bash

bootStrap.bash
I'm sorry for bothering again with a pull request, but the first shot was just too bad. This patch does away with some bad practices like not translating positional arguments into local variables immediately in dir_check(), adds option_name() helper function for more automation and replaces a hardcoded value for the default prefix value in usage() with a variable.
The patch has been tested and WFM.
=> [Build] Rework the patch adding the --prefix=DIR bootStrap.bash option

avidemux_core/ADM_core/src/ADM_cpuCap.cpp
Noticed during work on [EXCEPTION_ACCESS_VIOLATION in ADM_Composer::addFile(...) [avidemux_cli.exe]](http://avidemux.org/smif/index.php/topic,17055.0.html)
=> ADM_cpuCap.cpp : improve cosmetic for cpuCaps and cpuMask.

avidemux/qt4/i18n/avidemux_fr.ts
Fixes regression from [[i18n] More french update ](https://github.com/mean00/avidemux2/commit/ad9e09b7621d086bb5aaaaeea1a4de3db9870505)
=> Main menu: add 'R' accel key back.

bootStrap.bash
As building with external libass, liba52 and libmad is possible now, add respective options to bootStrap.bash.
=> [build] Add support for external libass, liba52 and libmad to bootStrap.bash

avidemux/qt4/i18n/avidemux_da.ts
Unfortunately, the translator for Danish seems to be discouraged by requests to change some aspects of his contribution. I'd like to submit [his work](https://github.com/mean00/avidemux2/pull/83) with these wishes addressed as an absolute exception and deviation from usual practices myself to avoid bitrot once the translation files get regenerated again soon.
=> [i18n] Update the Danish translation (scootergrisen)

avidemux/qt4/ADM_userInterfaces/ADM_gui/gui2.ui, avidemux/qt4/i18n/avidemux_ca.ts, avidemux/qt4/i18n/avidemux_cs.ts, avidemux/qt4/i18n/avidemux_da.ts, avidemux/qt4/i18n/avidemux_de.ts, avidemux/qt4/i18n/avidemux_el.ts, avidemux/qt4/i18n/avidemux_en.ts, avidemux/qt4/i18n/avidemux_es.ts, avidemux/qt4/i18n/avidemux_eu.ts, avidemux/qt4/i18n/avidemux_fr.ts, avidemux/qt4/i18n/avidemux_hu.ts, avidemux/qt4/i18n/avidemux_it.ts, avidemux/qt4/i18n/avidemux_ja.ts, avidemux/qt4/i18n/avidemux_pl.ts, avidemux/qt4/i18n/avidemux_pt_BR.ts, avidemux/qt4/i18n/avidemux_ru.ts, avidemux/qt4/i18n/avidemux_sr.ts, avidemux/qt4/i18n/avidemux_sr@latin.ts, avidemux/qt4/i18n/avidemux_tr.ts, avidemux/qt4/i18n/avidemux_zh_TW.ts
We've got quite a few new strings in very exposed locations.
=> I18n refresh

avidemux_plugins/ADM_videoFilters6/rotate/rotate.cpp
Let us please rotate clockwise, [Jan](http://avidemux.org/smif/index.php/topic,17606.0.html) has a point here.
=> [rotate] Rotate clockwise

avidemux/qt4/i18n/avidemux_da.ts
This last-minute patch adds Danish translations for the recently introduced preferences.
=> [i18n/da] Provide translations for the newly added preferences

avidemux/qt4/i18n/avidemux_ko.ts
Translation update for korean.
=> Translation update

cmake/admFFmpegBuild_helpers.cmake
This one always grinds my gears
=> Don't hardcode number of cpus used to build ffmpeg

avidemux/qt4/ADM_userInterfaces/ADM_gui/gui2.ui
This little thing annoys me every time i run the application
=> mainWindow > Audio tracks label - unified

avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2.cpp, avidemux/qt4/i18n/avidemux_pl.ts
=> PL translation update

cmake/admDetermineSystem.cmake, cmake/cmake_compile_check/cpu_arm64_check.cpp
This was enough to build and run, successfully transcoding a video.
=> Add support for Arm64

avidemux/qt4/i18n/avidemux_el.ts
Update of the Greek translation 002.
Spell checking not complete, due to problems with the translation tools.
=> Greek translation 002

avidemux/qt4/i18n/avidemux_el.ts
=> Greek translation 003

avidemux_plugins/ADM_videoEncoder/x265/ADM_x265.h, avidemux_plugins/ADM_videoEncoder/x265/ADM_x265Setup.cpp, avidemux_plugins/ADM_videoEncoder/x265/qt4/Q_x265.cpp, avidemux_plugins/ADM_videoEncoder/x265/qt4/x265ConfigDialog.ui, avidemux_plugins/ADM_videoEncoder/x265/x265_settings.conf, avidemux_plugins/ADM_videoEncoder/x265/x265_settings.h, avidemux_plugins/ADM_videoEncoder/x265/x265_settings_desc.cpp, avidemux_plugins/ADM_videoEncoder/x265/x265_settings_json.cpp
Fixed b-adapt not setting correctly.  The trellis quant stuff was leftover from x264.  I had wondered what that option did...
=> X265 fix badapt

avidemux_plugins/ADM_videoEncoder/x265/ADM_x265.h, avidemux_plugins/ADM_videoEncoder/x265/ADM_x265Setup.cpp, avidemux_plugins/ADM_videoEncoder/x265/qt4/Q_x265.cpp, avidemux_plugins/ADM_videoEncoder/x265/qt4/Q_x265.h, avidemux_plugins/ADM_videoEncoder/x265/qt4/x265ConfigDialog.ui, avidemux_plugins/ADM_videoEncoder/x265/x265_settings.conf, avidemux_plugins/ADM_videoEncoder/x265/x265_settings.h, avidemux_plugins/ADM_videoEncoder/x265/x265_settings_desc.cpp, avidemux_plugins/ADM_videoEncoder/x265/x265_settings_json.cpp
rdoq and psy-rdoq.  Almost done.  Just limit-modes is left.
I tried to copy the tab/space style of the surrounding code, but the existing code is not very consistent, so maybe some of the code isn't using the right one.
=> X265 options

avidemux_plugins/ADM_videoEncoder/x265/qt4/Q_x265.cpp
Storing a data value with each combo box item makes things a lot easier.
=> Use data for the combo boxes

avidemux_plugins/ADM_videoFilters6/resize/qt4/Q_resize.cpp, avidemux_plugins/ADM_videoFilters6/resize/qt4/Q_resize.h, avidemux_plugins/ADM_videoFilters6/resize/qt4/resizing.ui, avidemux_plugins/ADM_videoFilters6/resize/swScaleResize.cpp, avidemux_plugins/ADM_videoFilters6/resize/swresize.conf, avidemux_plugins/ADM_videoFilters6/resize/swresize.h, avidemux_plugins/ADM_videoFilters6/resize/swresize_desc.cpp, avidemux_plugins/ADM_videoFilters6/resize/swresize_json.cpp
I know, from a technical viewpoint only mod16 makes sense, however its inconvenient from the user's viewpoint.
It is on multpile user's wishlist (including mine :) ).
=> [resize] more rounding options

avidemux_plugins/ADM_videoFilters6/asharp/ADM_vidAsharp.cpp, avidemux_plugins/ADM_videoFilters6/asharp/DIA_flyAsharp.cpp, avidemux_plugins/ADM_videoFilters6/asharp/asharp.conf, avidemux_plugins/ADM_videoFilters6/asharp/asharp.h, avidemux_plugins/ADM_videoFilters6/asharp/asharp_desc.cpp, avidemux_plugins/ADM_videoFilters6/asharp/asharp_json.cpp, avidemux_plugins/ADM_videoFilters6/asharp/qt4/Q_asharp.cpp, avidemux_plugins/ADM_videoFilters6/asharp/qt4/asharp.ui
Backend code behaviour: 
>Adaptive strength is enabled when the D parameter > 0. Disabled if == 0.
>Block adaptive sharpening is disabled ,when the B parameter is negative.
For clarity, checkboxes were added, to handle enabled/disabled states.
=> [asharp/qt4] UI add checkboxes for proper enable/disable option

avidemux_plugins/ADM_videoFilters6/crop/ADM_vidCrop.cpp, avidemux_plugins/ADM_videoFilters6/crop/crop.conf, avidemux_plugins/ADM_videoFilters6/crop/crop.h, avidemux_plugins/ADM_videoFilters6/crop/crop_desc.cpp, avidemux_plugins/ADM_videoFilters6/crop/qt5/DIA_flyCrop.cpp, avidemux_plugins/ADM_videoFilters6/crop/qt5/DIA_flyCrop.h, avidemux_plugins/ADM_videoFilters6/crop/qt5/Q_crop.h, avidemux_plugins/ADM_videoFilters6/crop/qt5/crop.ui
Option for select (other than the source's) aspect ratio for the "Keep aspect ratio" mode.
=> [crop/qt5] select aspect ratio comboBox for keep aspect ratio

avidemux/qt4/ADM_UIs/include/DIA_flyDialogQt4.h, avidemux/qt4/ADM_UIs/src/T_RubberControl.cpp, avidemux_plugins/ADM_videoFilters6/blackenBorder/qt5/DIA_flyBlackenBorders.cpp, avidemux_plugins/ADM_videoFilters6/blackenBorder/qt5/DIA_flyBlackenBorders.h, avidemux_plugins/ADM_videoFilters6/crop/qt5/DIA_flyCrop.cpp, avidemux_plugins/ADM_videoFilters6/crop/qt5/DIA_flyCrop.h, avidemux_plugins/ADM_videoFilters6/mplayerDelogo/qt5/DIA_flyMpDelogo.cpp, avidemux_plugins/ADM_videoFilters6/mplayerDelogo/qt5/DIA_flyMpDelogo.h
Extended rubber control with drag.
Also adapted all filter that use rubber control (crop, blacken border, mplayer delogo)
=> Draggable rubberband

avidemux_plugins/ADM_videoFilters6/artCharcoal/ADM_vidArtCharcoal.cpp
+40% fps
on my old i5 it can reach  80fps@1080p (i think it sufficient, as few useful encoder can keep up with this frame rate )
=> [artCharcoal] Optimize more

avidemux_plugins/ADM_videoFilters6/fastConvolution/Median.cpp
=> [fastConvolution/Median] Optimize core

avidemux_plugins/ADM_videoFilters6/negative/ADM_negative.cpp
=> [negative] fix uniq internal name

avidemux_plugins/ADM_videoFilters6/colorBalance/ADM_vidColorBalance.cpp
=> [colorBalance] bugfix

avidemux_plugins/ADM_videoFilters6/eq2/ADM_vidEq2.cpp
Fix bug introduced in commit 57a5b6b.
(Red and blue sliders were swapped).
=> [eq2] bugfix

avidemux_plugins/ADM_videoFilters6/artVignette/qt4/Q_artVignette.cpp, avidemux_plugins/ADM_videoFilters6/artVignette/qt4/Q_artVignette.h, avidemux_plugins/ADM_videoFilters6/artVignette/qt4/artVignette.ui
Is this okay qt signalingwise?
=> [artVignette] add coupled spinboxes

avidemux_plugins/ADM_videoFilters6/artGrid/qt4/Q_artGrid.cpp, avidemux_plugins/ADM_videoFilters6/artGrid/qt4/Q_artGrid.h, avidemux_plugins/ADM_videoFilters6/artGrid/qt4/artGrid.ui, avidemux_plugins/ADM_videoFilters6/artPosterize/qt4/DIA_flyArtPosterize.h, avidemux_plugins/ADM_videoFilters6/artPosterize/qt4/Q_artPosterize.cpp, avidemux_plugins/ADM_videoFilters6/artPosterize/qt4/Q_artPosterize.h, avidemux_plugins/ADM_videoFilters6/artPosterize/qt4/artPosterize.ui, avidemux_plugins/ADM_videoFilters6/blur/qt4/DIA_flyBlur.h, avidemux_plugins/ADM_videoFilters6/blur/qt4/Q_blur.cpp, avidemux_plugins/ADM_videoFilters6/blur/qt4/Q_blur.h, avidemux_plugins/ADM_videoFilters6/blur/qt4/blur.ui, avidemux_plugins/ADM_videoFilters6/waveletDenoise/qt4/Q_waveletDenoise.cpp, avidemux_plugins/ADM_videoFilters6/waveletDenoise/qt4/Q_waveletDenoise.h, avidemux_plugins/ADM_videoFilters6/waveletDenoise/qt4/waveletDenoise.ui, avidemux_plugins/ADM_videoFilters6/waveletSharp/qt4/Q_waveletSharp.cpp, avidemux_plugins/ADM_videoFilters6/waveletSharp/qt4/Q_waveletSharp.h, avidemux_plugins/ADM_videoFilters6/waveletSharp/qt4/waveletSharp.ui
=> Add spinboxes

avidemux_plugins/ADM_videoFilters6/asciiView/ADM_vidAscii.cpp
IMHO the "Artistic" category is a 100% fit for this filter :)
=> [asciiView] change category

avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2.cpp, avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2.h
Keep playing if navigation slider has been dragged.
=> [Q_gui2] resume playing on slider drag

avidemux/common/ADM_videoFilter2/src/ADM_vidPartial.cpp
take start/stop times from the filter chain
=> [ADM_vidPartial] get marker info from the filter chain

avidemux/cli/ADM_userInterfaces/ADM_gui2/gui_none.cpp, avidemux/common/ADM_commonUI/GUI_ui.h, avidemux/common/gui_navigate.cpp, avidemux/qt4/ADM_userInterfaces/ADM_gui/ADM_mwNavSlider.cpp, avidemux/qt4/ADM_userInterfaces/ADM_gui/ADM_mwNavSlider.h, avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2.cpp
Mark append and cut points on the navigation slider.
The next developement step could be buttons+shortcuts to jump to these points.
=> [GUI] show segment boundaries on the navigation slider

avidemux_core/ADM_coreUtils/src/avidemutils.cpp, avidemux_plugins/ADM_videoFilters6/changeFps/changeFps.cpp, avidemux_plugins/ADM_videoFilters6/resampleFps/ADM_vidResampleFPS.cpp
=> Increase max fps to 1000

avidemux_plugins/ADM_videoFilters6/quadTrans/ADM_vidQuadTrans.cpp
=> [quadTrans] fix rare crash

avidemux_core/ADM_coreImage/include/ADM_colorspace.h, avidemux_core/ADM_coreImage/src/ADM_colorspace.cpp, avidemux_plugins/ADM_videoFilters6/resize/qt4/resizing.ui, avidemux_plugins/ADM_videoFilters6/resize/swScaleResize.cpp
sometimes can be useful (pixel art / old game captures)
=> [resize] add nearest neighbor algo

avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2.cpp, avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2.h
give feedback during navigation
=> [Q_gui2] show busy cursor during navigation

avidemux_plugins/ADM_videoFilters6/resampleFps/motin.cpp
=> [resampleFps/motin] reduce artifacts

avidemux_plugins/ADM_videoFilters6/quadTrans/ADM_vidQuadTrans.cpp, avidemux_plugins/ADM_videoFilters6/quadTrans/ADM_vidQuadTrans.h, avidemux_plugins/ADM_videoFilters6/quadTrans/CMakeLists.txt
- backport multithreaded processing from imageStab
- apply transform directly on YUV image
=> [quadTrans] performance improvements

avidemux_plugins/ADM_videoFilters6/imageStab/ADM_vidImageStab.cpp, avidemux_plugins/ADM_videoFilters6/imageStab/ADM_vidImageStab.h, avidemux_plugins/ADM_videoFilters6/imageStab/motest.cpp
- faster fast motion estimation
- apply transform directly on YUV image
=> [imageStab] performance improvements

avidemux/winInstaller/ChangeLog.release
=> changelog update

avidemux/qt4/ADM_userInterfaces/ADM_dialog/Q_props.cpp, avidemux/qt4/ADM_userInterfaces/ADM_dialog/props.ui, avidemux_core/ADM_coreDemuxer/include/ADM_Video.h, avidemux_core/ADM_coreDemuxer/src/ADM_demuxer.cpp, avidemux_plugins/ADM_demuxers/Flv/ADM_flv.cpp, avidemux_plugins/ADM_demuxers/Flv/ADM_flv.h, avidemux_plugins/ADM_demuxers/Matroska/ADM_mkv.cpp, avidemux_plugins/ADM_demuxers/Matroska/ADM_mkv.h, avidemux_plugins/ADM_demuxers/Mp4/ADM_mp4.cpp, avidemux_plugins/ADM_demuxers/Mp4/ADM_mp4.h
for now only works with mkv/webm and mp4 containers (but these are the most common nowadays)
=> [Q_props] display average video bitrate if available

avidemux_plugins/ADM_videoFilters6/imageStab/ADM_vidImageStab.cpp, avidemux_plugins/ADM_videoFilters6/imageStab/ADM_vidImageStab.h
=> [imageStab] fix header

avidemux_plugins/ADM_videoFilters6/fadeFromImage/ADM_vidFadeFromImage.cpp, avidemux_plugins/ADM_videoFilters6/fadeFromImage/fadeFromImage.conf, avidemux_plugins/ADM_videoFilters6/fadeFromImage/fadeFromImage.h, avidemux_plugins/ADM_videoFilters6/fadeFromImage/fadeFromImage_desc.cpp, avidemux_plugins/ADM_videoFilters6/fadeFromImage/fadeFromImage_json.cpp, avidemux_plugins/ADM_videoFilters6/fadeFromImage/qt4/Q_fadeFromImage.cpp, avidemux_plugins/ADM_videoFilters6/fadeFromImage/qt4/Q_fadeFromImage.h, avidemux_plugins/ADM_videoFilters6/fadeFromImage/qt4/fadeFromImage.ui
- UI direction input simplified to combobox
+Push effect
=> [fadeFromImage] simplify direction input; add Push effect

avidemux_plugins/ADM_videoFilters6/fadeThrough/ADM_vidFadeThrough.cpp, avidemux_plugins/ADM_videoFilters6/fadeThrough/ADM_vidFadeThrough.h, avidemux_plugins/ADM_videoFilters6/fadeThrough/qt4/Q_fadeThrough.cpp, avidemux_plugins/ADM_videoFilters6/fadeThrough/qt4/fadeThrough.ui
Blur spinbox fix, slider tooltips removed.
Calculate YUV blend parameters only when necessary.
I left out adjustSize(), because it makes the preview super tiny. Maybe You can solve this.
=> Fadethrough fix

avidemux_plugins/ADM_videoFilters6/waveletSharp/ADM_vidWaveletSharp.cpp, avidemux_plugins/ADM_videoFilters6/waveletSharp/ADM_vidWaveletSharp.h, avidemux_plugins/ADM_videoFilters6/waveletSharp/qt4/DIA_flyWaveletSharp.cpp, avidemux_plugins/ADM_videoFilters6/waveletSharp/qt4/Q_waveletSharp.cpp, avidemux_plugins/ADM_videoFilters6/waveletSharp/qt4/waveletSharp.ui, avidemux_plugins/ADM_videoFilters6/waveletSharp/waveletSharp.conf, avidemux_plugins/ADM_videoFilters6/waveletSharp/waveletSharp.h, avidemux_plugins/ADM_videoFilters6/waveletSharp/waveletSharp_desc.cpp, avidemux_plugins/ADM_videoFilters6/waveletSharp/waveletSharp_json.cpp
I had an idea, and it looks like it greatly improves the quality of this sharpener.
Increasing the cutoff parameter can totally eliminate sharpening of compression artifacts (blocking) and small noise.
=> [waveletSharp] add cutoff parameter

avidemux_plugins/ADM_videoFilters6/resampleFps/motin.cpp, avidemux_plugins/ADM_videoFilters6/resampleFps/motin.h
less artifacts
30-40% faster (at least on an 8 core+HT machine)
=> [resampleFps/motin] quality and performance improvements

avidemux/common/gui_blackframes.cpp
go to the prev key frame, check forward up to the current position, if not found set the keyframe as the current position, then repeat
=> [gui_blackframes] fast backward search

avidemux_plugins/ADM_videoFilters6/zoom/ADM_vidZoom.cpp, avidemux_plugins/ADM_videoFilters6/zoom/qt5/zoom.ui
=> [zoom] add option for stretching (no padding)

avidemux/common/gui_action.names, avidemux/common/gui_navigate.cpp, avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2.cpp, avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2.h
enable backward/forward time jumps (1,2,4,60sec) and gotomarkers.
=> [GUI] enable some navigation during play

avidemux_plugins/ADM_videoFilters6/eq2/ADM_vidEq2.cpp
there was a slight, but noticeable green tint even with default settings.
=> [eq2] fix green tint

avidemux_plugins/ADM_videoEncoder/x264/ADM_x264.h, avidemux_plugins/ADM_videoEncoder/x265/ADM_x265.h
x264 & x265 encoders:
-"Use advanced configuration" unchecked
-default preset is medium
=> Encoder defaults

avidemux/common/ADM_audioFilter/src/audiofilter_thread.cpp, avidemux/common/ADM_videoFilter2/src/ADM_filterThread.cpp, avidemux_core/ADM_coreUtils/include/ADM_threadQueue.h, avidemux_core/ADM_coreUtils/src/ADM_threadQueue.cpp
-fix stopping issue  (half second delay) during playback (which resulted very slow navigation during play)
-always access threadState exclusively
=> [ADM_threadQueue] bugfix + exclusive access for state variable

avidemux_core/ADM_coreImage/src/ADM_imageSave.cpp
=> [ADM_imageSave] multithreading saveAsJpgInternal

avidemux_core/ADM_coreImage/src/ADM_toneMapper.cpp
=> [ADM_toneMapper] improve boosting of fast yuv mapper

avidemux_core/ADM_coreImage/include/ADM_toneMapper.h, avidemux_core/ADM_coreImage/src/ADM_toneMapper.cpp
-much better/accurate colors
-significantly faster (almost x2 faster on many core CPU)
=> [ADM_toneMapper/RGB] bugfixes and performance improvements

avidemux_plugins/ADM_videoFilters6/delogoHQ/ADM_vidDelogoHQ.cpp, avidemux_plugins/ADM_videoFilters6/delogoHQ/ADM_vidDelogoHQ.h, avidemux_plugins/ADM_videoFilters6/delogoHQ/qt4/DIA_flyDelogoHQ.cpp, avidemux_plugins/ADM_videoFilters6/delogoHQ/qt4/DIA_flyDelogoHQ.h, avidemux_plugins/ADM_videoFilters6/delogoHQ/qt4/Q_delogoHQ.cpp, avidemux_plugins/ADM_videoFilters6/delogoHQ/qt4/delogoHQ.ui
+make more vertical space in UI
=> [delogoHQ] operate on linear intensity; better quality gradient

avidemux/common/ADM_commonUI/DIA_postproc.cpp, avidemux/common/ADM_editor/src/ADM_edRenderInternal.cpp, avidemux/common/gui_action.names, avidemux/common/gui_main.cpp, avidemux/common/gui_navigate.cpp, avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2.cpp, avidemux_core/ADM_coreImage/src/ADM_pp.cpp
-show postporc settings changes in the shown frame (similar as tonemapping)
-separate deblocking parameters from deinterlacing (strength does'nt affect deinterlacing)
-make deblocking functional
=> PostProcessing improvements

avidemux/common/ADM_commonUI/DIA_HDRConfig.cpp, avidemux/common/ADM_commonUI/DIA_prefs.cpp, avidemux_core/ADM_coreImage/include/ADM_toneMapper.h, avidemux_core/ADM_coreImage/src/ADM_toneMapper.cpp
+fix limited range YCbCr to RGB conversion
=> [hdr] adaptive RGB tonemappers

avidemux/common/ADM_commonUI/DIA_HDRConfig.cpp, avidemux/common/ADM_commonUI/DIA_prefs.cpp, avidemux/common/ADM_editor/include/ADM_edit.hxx, avidemux/common/ADM_editor/include/IEditor.h, avidemux/common/ADM_editor/src/ADM_edRender.cpp, avidemux/common/ADM_editor/src/utils/ADM_edScriptGenerator.cpp, avidemux/common/gui_main.cpp, avidemux_core/ADM_coreImage/include/ADM_toneMapper.h, avidemux_core/ADM_coreImage/src/ADM_toneMapper.cpp, avidemux_core/ADM_coreScript/include/IScriptWriter.h, avidemux_core/ADM_coreUI/include/DIA_factory.h, avidemux_plugins/ADM_scriptEngines/qtScript/src/QtScriptWriter.cpp, avidemux_plugins/ADM_scriptEngines/qtScript/src/QtScriptWriter.h, avidemux_plugins/ADM_scriptEngines/tinyPy/src/PythonScriptWriter.cpp, avidemux_plugins/ADM_scriptEngines/tinyPy/src/PythonScriptWriter.h, avidemux_plugins/ADM_scriptEngines/tinyPy/src/adm_gen.cpp, avidemux_plugins/ADM_scriptEngines/tinyPy/src/binding/adm.admPyClass
-move adaptive option to a checkbox (default: checked)
-try to match levels between all adaptive RGB tonemappers
-add comments, replace some magic numbers with defines, rename variables to match functionality
=> [hdr] adaptive RGB checkbox + gamut control option

avidemux/common/ADM_audioFilter/src/audiofilter.cpp, avidemux/common/ADM_audioFilter/src/audiofilter_mixer.cpp, avidemux/common/ADM_commonUI/DIA_audioFilter.cpp, avidemux/common/ADM_commonUI/DIA_prefs.cpp, avidemux_core/ADM_coreAudio/include/ADM_audiodef.h, avidemux_core/ADM_coreAudioFilter/include/audiofilter_mixer.h, avidemux_core/ADM_coreUtils/src/prefs2.conf, avidemux_core/ADM_coreUtils/src/prefs2_pref.h
=> [audiofilter_mixer] Surround headphone downmix option

avidemux_plugins/ADM_videoFilters6/resampleFps/motin.cpp
=> [resampleFps/motin] fix exception access violation

avidemux_plugins/ADM_videoFilters6/resampleFps/ADM_vidResampleFPS.cpp
it's simpler than i initially thought
=> [resampleFps] do motion estimation on demand

avidemux/qt4/ADM_userInterfaces/ADM_gui/T_thumbSlider.cpp
- prevent creating multiple timer
- fix scrolling out of range
- remove lag
=> [T_thumbSlider] bugfixes

avidemux_core/ADM_core/include/ADM_cpuSIMD.h, avidemux_core/ADM_core/include/sse2neon.h, avidemux_plugins/ADM_videoFilters6/aiEnhance/FSRCNN.cpp, avidemux_plugins/ADM_videoFilters6/aiEnhance/NeuronSW.cpp, avidemux_plugins/ADM_videoFilters6/aiEnhance/NeuronSW.h, avidemux_plugins/ADM_videoFilters6/aiEnhance/fastFSRCNN.cpp, avidemux_plugins/ADM_videoFilters6/imageStab/motest.cpp, avidemux_plugins/ADM_videoFilters6/resampleFps/motin.cpp
=> [resampleFps/motin] & [imageStab/motest] use SIMD intrinsics

avidemux/common/ADM_commonUI/DIA_prefs.cpp, avidemux_core/ADM_core/include/ADM_cpuCap.h, avidemux_core/ADM_core/include/ADM_cpuSIMD.h, avidemux_core/ADM_core/src/ADM_cpuCap.cpp, avidemux_plugins/ADM_videoFilters6/aiEnhance/ADM_vidAiEnhance.cpp, avidemux_plugins/ADM_videoFilters6/aiEnhance/ADM_vidAiEnhance.h, avidemux_plugins/ADM_videoFilters6/aiEnhance/FSRCNN.cpp, avidemux_plugins/ADM_videoFilters6/aiEnhance/FSRCNN.h, avidemux_plugins/ADM_videoFilters6/aiEnhance/NeuronSW.cpp, avidemux_plugins/ADM_videoFilters6/aiEnhance/NeuronSW.h, avidemux_plugins/ADM_videoFilters6/aiEnhance/fastFSRCNN.cpp, avidemux_plugins/ADM_videoFilters6/aiEnhance/fastFSRCNN.h
=> [aiEnhance] refactor; AVX + FMA

avidemux/common/ADM_render/GUI_xvRender.cpp
this prevent green flash on video loading
=> [GUI_xvRender] initialize to black

avidemux_plugins/ADM_videoFilters6/fitToSize/qt4/Q_fitToSize.cpp, avidemux_plugins/ADM_videoFilters6/fitToSize/qt4/Q_fitToSize.h, avidemux_plugins/ADM_videoFilters6/fitToSize/qt4/fitToSize.ui
using UTF-8 "⇄" as button text
hopes it works anywhere
=> [fitToSize] swap dimensions button

avidemux/common/main.cpp, avidemux/qt4/ADM_jobs/src/ADM_jobs.cpp, avidemux_core/ADM_coreDemuxerMpeg/include/ADM_indexFile.h, avidemux_core/ADM_coreDemuxerMpeg/src/ADM_indexFile.cpp, avidemux_core/ADM_coreUtils/include/ADM_memFile.h, avidemux_core/ADM_coreUtils/src/ADM_memFile.cpp, avidemux_core/ADM_coreUtils/src/ADM_quota.cpp, avidemux_core/ADM_coreUtils/src/CMakeLists.txt, avidemux_plugins/ADM_demuxers/MpegTS/ADM_ts.cpp, avidemux_plugins/ADM_demuxers/MpegTS/ADM_ts.h, avidemux_plugins/ADM_demuxers/MpegTS/ADM_tsIndex.cpp, avidemux_plugins/ADM_demuxers/MpegTS/ADM_tsIndex.h, avidemux_plugins/ADM_demuxers/MpegTS/ADM_tsIndexH264.cpp, avidemux_plugins/ADM_demuxers/MpegTS/ADM_tsIndexH265.cpp, avidemux_plugins/ADM_demuxers/MpegTS/ADM_tsIndexMpeg2.cpp, avidemux_plugins/ADM_demuxers/MpegTS/ADM_tsIndexVC1.cpp
=> [MpegTS] index file in memory 

avidemux/qt4/ADM_render_qt/GUI_xvRender.cpp
=> [GUI_xvRender] allow multiple instance to use Xv render
