avidemux_core/ADM_core/src/ADM_debug.cpp
32m is really green.  return color to default after printing
avidemux frequently leaves the font color as green when it exits.  This fixes that by consistently resetting to default after printing in color.
=> fix up colors in the terminal

avidemux/qt4/ADM_userInterfaces/ADM_gui/file_qt4.cpp
In current avidemux 2.6.10 the File->Open file browser opens in the
LASTFILES_LASTDIR_WRITE directory, which is updated whenever a file
is written.
This patch corrects this behaviour to open the browser in the last
directory that has been read from.
=> [qt4] Open video files in LASTFILES_LASTDIR_READ directory

avidemux/common/gui_save.cpp, avidemux/qt4/ADM_userInterfaces/ADM_gui/file_qt4.cpp
Provide a default (selected) filename when saving video, or when saving
a video frame to BMP/JPEG.
The default filename is constructed from the basename of the current open
video, with an extension determined by the output container/image format.
If the user does not want to use the default filename, they can simply
start typing to replace the selected filename with one of their choosing.
This update also has the effect of filtering the files displayed in the
FileDialog to those having the same extension.
=> [qt4] Provide a default filename when saving

avidemux/qt4/ADM_userInterfaces/ADM_gui/file_qt4.cpp
Always prompt the user before overwriting a file in the output directory
which has the same filename, when file filtering in the FileDialog is enabled.
This change should be applied after the update to provide a default filename
(including extension) when saving video/images.
Currently:
When file filtering is enabled, a file extension is automatically
added when the output filename does not contain a dot ("."). This is also
the time when ADM checks if the output file exists after adding the
filtering extension.
With ADM updated to suggest a default filename when saving, this file check
might not happen (because the output filename will probably already contain
a dot (".")).
This update tries to ensure that the user is always prompted before
overwriting a file when saving.
=> [qt4] Avoid overwriting output files when saving video/images

avidemux/common/ADM_editor/src/ADM_edit.cpp, avidemux/common/ADM_videoCodec/src/ADM_ffmpeg_libva.cpp, avidemux/common/ADM_videoCodec/src/ADM_ffmpeg_vdpau.cpp, avidemux/common/ADM_videoCodec/src/ADM_ffmpeg_xvba.cpp, avidemux/common/gui_autodrive.cpp, avidemux/common/gui_main.cpp, avidemux/common/gui_navigate.cpp, avidemux/common/gui_savenew.cpp, avidemux_plugins/ADM_muxers/muxerAvi/muxerAvi.cpp, avidemux_plugins/ADM_muxers/muxerMp4v2/muxerMp4v2.cpp, avidemux_plugins/ADM_muxers/muxerMp4v2/muxerMp4v2Audio.cpp, avidemux_plugins/ADM_muxers/muxerWebm/muxerWebm.cpp, avidemux_plugins/ADM_videoEncoder/x264/ADM_x264Setup.cpp, avidemux_plugins/ADM_videoEncoder/x265/ADM_x265Setup.cpp, myOwnPlugins/muxer/muxerLmkvAudio.cpp
Fix typos and improve consistency of some error messages.
I have tried to avoid changing translatable strings where possible.
=> Fix typos and improve consistency of some error messages

avidemux_plugins/ADM_videoEncoder/x264/qt4/Q_x264.cpp, avidemux_plugins/ADM_videoEncoder/x265/qt4/Q_x265.cpp
gcc complains again about narrowing conversion
=> Explicitly cast to unsigned int

avidemux/common/main.cpp
There's a cleanup method for video decoders.  This calls the method during shutdown and fixes some additional leaks.
=> Call ADM_vd6_cleanup on shutdown

avidemux_core/ADM_coreUtils/src/ADM_last.cpp
Leftover from https://github.com/mean00/avidemux2/commit/7c55704afc2f564437a3a283d458743423bd4a86.
(Trivial. Untested.)
=> Remove (now) unused "tmp" var.

avidemux_plugins/ADM_demuxers/MpegTS/ADM_tsIndexH264.cpp
Fix [[index/h264] deal more nicely with corrupted input while decoding SEI](https://github.com/mean00/avidemux2/commit/0eaee7e93475dc4516dd000faf1eb6127527bd3c),
plus 2 other cases.
=> ADM_tsIndexH264.cpp, printf : fix 2 %d, improve 1 %x.

avidemux/common/ADM_editor/src/ADM_segment.cpp
I realized too late that ADM_EditorSegment::appendFromClipBoard could use the same shortcut if the clipboard is empty, just for the sake of economy. Now as a formal push request.
=> [Editor] Do not try to append from empty clipboard

avidemux/common/ADM_commonUI/myOwnMenu.h, avidemux/common/ADM_editor/include/ADM_edit.hxx, avidemux/common/ADM_editor/include/ADM_segment.h, avidemux/common/ADM_editor/src/ADM_segment.cpp, avidemux/common/ADM_editor/src/CMakeLists.txt, avidemux/common/ADM_editor/src/utils/ADM_edUndoQueue.cpp, avidemux/common/gui_action.names, avidemux/common/gui_main.cpp
My apologies for being impatient. This patch implements a unified undo/redo queue both for segments and markers, moving the undo functionality from segment management one level higher into the composer and adding a "Redo" item with Ctrl+Y shortcut to the "Edit" menu. The new functions `ADM_Composer::addToUndoQueu`, `ADM_Composer::undo`, `ADM_Composer::redo` and `ADM_Composer::clearUndoQueue` get called now directly from UI actions.
A few notes: Undoing or redoing a cut/delete/paste operation bypasses the position adjustment logic implemented in ACT_Cut/Delete/Paste. This is a design limitation. Ideally, the undo queue would become action-aware and the implementation would provide a clue for GUI to disable not applicable options.
While I can't tell from my zero level of experience if the …
=> [Editor][UI] Add unified undo/redo for segments and markers

avidemux_plugins/ADM_videoEncoder/x264/qt4/Q_x264.cpp, avidemux_plugins/ADM_videoEncoder/x265/qt4/Q_x265.cpp
This patch adds null/none tuning as the default tuning for x264 and x265 encoders if the advanced configuration is disabled and makes the label "none" translatable. Furthermore, it adds `grain` to the `ListOfTunings` array for x265.
This is basically [[x265/Qt] Add none preset (eumagga0x2a)](https://github.com/mean00/avidemux2/commit/6bb59711f290291c532bd60f37513e3b04d763e3), but finally done right (hopefully).
=> [x264/Qt][x265/Qt] Add translatable default none tuning

avidemux/common/ADM_commonUI/DIA_prefs.cpp
This patch fixes or rather works around the keyboard navigation issue described in [Strange tab order in Edit / Prefences / Display](http://avidemux.org/smif/index.php/topic,16972.0.html). It seems that there is currently no way to set tabbing order of dialog elements unambiguously, which means that elements get ordered in "first come, first served" manner. Oddly enough, this doesn't lead to problems except of in the Display tab of the preferences dialog, where the tabbing order is very wrong.
The patch combines three top-level elements into a second frame, ordered below the first one. This is enough to correct the tabbing order, according to my testing, and looks quit similar to the current design.
The title of the additional frame, "GUI Rendering Options", seems to match the meaning of …
=> [UI] Work around tabbing order issues in the 'Display' tab of the preferences dialog

avidemux_plugins/ADM_demuxers/MpegPS/ADM_psIndex.cpp
Apply the same logic as in `avidemux_plugins/ADM_demuxers/MpegTS/ADM_tsIndexMpeg2.cpp:123` and don't round up the height of the video to a multiple of 16.
Reference: [MPEG-2 resolution 1920x1080 opened and encoded with 1920x1088](http://avidemux.org/smif/index.php/topic,17258.0.html).
=> [Demuxer/MpegPS] Do not round up the height to a multiple of 16

avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2.cpp
This patch fixes `UI_deiconify` to take the last window state into account instead of always trying to restore to a normal window (Avidemux window retaining the maximized state when manually restored from "tray" on Linux even without this patch must be a bug in gnome-shell or Qt).
While tested WFM on Linux, I'm pretty confident that this patch should fix the issue on Windows as well.
Reference: [Avidemux 2.6.4 - Minimize to notification area](http://avidemux.org/smif/index.php/topic,12493.0.html)
=> [Qt] Restore correct window state upon finishing encoding while minimized to notification area

avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2.cpp
I think I've nailed it. Though not yet tested on Windows, I'm pretty confident that this would work reliably everywhere and look good with all font sizes.
The earlier attempt [[ui/qt] bigger time display (flexible/euma)](https://github.com/mean00/avidemux2/commit/c9d2a656a6122f9dd27687a5b4d8fb7326393489) turned out to be a waste of your time, my apologies. As feared, the results didn't look good on Windows with usual tiny fonts.
=> [Qt] Set the size of time display to fit the content

avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2.cpp
This should be enough to avoid clipping with the breeze theme.
=> [Qt] Make the time display 4px wider to avoid clipping with breeze Qt theme

cmake/admFFmpegBuild_native.cmake
As of [[core/ffmpeg] fix patching ](https://github.com/mean00/avidemux2/commit/6df6ec6d4e0c1d951df3b1748f5efd85efcbb1ef) the code in `cmake/admFFmpegBuild_native.cmake:18` tries to patch common.mak no matter what, breaking the build with --rebuild option as a result. This patch takes into account the value of the `FFMPEG_PERFORM_PATCH` env variable.
=> [Core/FFmpeg] Do not try to patch already patched common.mak, unbreak --rebuild option

avidemux/common/gui_main.cpp
On Fedora and probably other distributions with GNOME and gdm as display manager the default value for $DESKTOP is `:1` for the local display, thus resulting in hardware accelerated video output in Avidemux wrongly disabled. Let us please disable the check for `$DISPLAY` == `:0` which does much more harm than good.
=> [UI/Render] Disable faulty check for remote display breaking VDPAU

cmake/admFFmpegBuild_helpers.cmake, cmake/admFFmpegPrepareGit.cmake
I wonder if it is just the videolan.org git mirror which is so unbearably slow, maybe switching to ffmpeg.org would work better if this feature ever gets used.
The archiving part is untested, unfortunately, but should work, hopefully. It can't work without the second patch, obviously, as `TAR_EXECUTABLE` remains unset then.
=> [Build/FFmpeg] Fix FFmpeg checkout from git as fallback and archiving

avidemux_core/ADM_coreUtils/src/prefs.cpp
`preferences::load` returning `true` on error deserializing prefs struct led to "Dummy" audio device being selected if new preference settings were added or old ones removed, because `setPrefsDefault()` was not run within `startAvidemux` function in `avidemux/common/main.cpp` in this case.
Reference: [No sound during playback of any video file using latest version of Avidemux](http://avidemux.org/smif/index.php/topic,17290.0.html)
=> [Pref] Return false if loading config fails, avoid selecting dummy audio device in this case

avidemux_plugins/ADM_videoEncoder/x265/qt4/Q_x265.cpp, avidemux_plugins/ADM_videoEncoder/x265/qt4/Q_x265.h
Allowing users to increase the number of ref frames up to 16 and then rejecting the codec setup with an error message which doesn't mention the true reason why it appears is a bad idea. Enforce the HEVC specs compliance in the dialog to avoid user confusion.
Reference: [settting X265 to more than 6 ref frames hass error](http://avidemux.org/smif/index.php/topic,17285.0.html).
=> [Qt/x265] Limit the number of ref frames in compliance with HEVC specs

createDebFromSourceUbuntu.bash
This patch adds the following options to the Ubuntu build script:
1. to install build dependencies only;
2. to build but not to install the generated debs;
3. to keep build directories from the previous run;
4. an ability to specify install prefix with sanity checks duplicated from bootStrap.bash to fail immediately on a bad prefix.
It also saves the messages printed to the terminal to a `log-bootstrap-<DATE>_<TIME>.log` file.
=> [Build] Add options to Ubuntu build script

avidemux_core/ADM_coreUtils/src/ADM_paramList.cpp
Ignoring the return value of ADM_paramValidatePartialList prevents Avidemux from unnecessarily discarding configuration on version update. According to my testing with added or removed entries in config3 this is reasonably safe (the only crash I experienced – unrecoverable without fixing or deleting the config3 file manually  – happens independently of this patch). Type validation is provided to some degree within the `ADM_paramLoadInternal` function.
=> [core/prefs] Accept too long or incomplete partial parameter lists

cmake/admCheckNvEnc.cmake, cmake/admFFmpegBuild_native.cmake
This fixes NVENC detection and ffmpeg configuration during a native build on Fedora. Tested working in MXE as well.
=> [build/cmake] Fix NVENC detection and ffmpeg configure options

avidemux/qt4/i18n/avidemux_fr.ts
=> avidemux_fr.ts

avidemux/common/A_functions.h, avidemux/common/gui_navigate.cpp
These changes implement seeking to all types of frames, allowing precise navigation (1/2/4s steps and go to time) with some special treatment for seeking to zero or to time beyond the end of the video.
=> [UI] Fix navigation in 1/2/4s steps

avidemux/qt4/ADM_userInterfaces/ADM_gui/gui2.ui
Currently the top edge of the mute button gets clipped with the "fusion" Qt theme, the spacer results in a much too big distance between the button and the slider and the button and the slider are not aligned:
This patch centers the button and the slider horizontally and gets rid of the spacer and zero top margin for the button, avoiding clipping:
Tested WFM on Windows as well.
=> [Qt] Align the mute button and the volume slider, avoid clipping

avidemux/common/gui_navigate.cpp
Oops, there were some editing leftovers in the last commit. Also don't try to call `goToTimeVideo` with `pts` equal zero, it spits a ton of terrifying errors if it fails, just call `rewind()`.
My apologies for the trouble.
=> [UI] Remove forgotten unused variable and simplify handling of pts==0 in A_jumpToTime

avidemux/common/ADM_render/GUI_vdpauRender.h
Displaying "VDPAU" for video output and "Vdpau" a few pixels to the right for video decoder looked a bit strange for me. Adjust the case of the latter to match the former and the convention.
=> [cosmetics] Show an uppercase string as decoder name for VDPAU

avidemux/qt4/ADM_userInterfaces/ADM_gui/gui2.ui
As evident from screenshots in [https://github.com/mean00/avidemux2/pull/54](https://github.com/mean00/avidemux2/pull/54), the width of the selection widget is excessive, wasting space to the left of the volume widget. With the proposed change it would look as follows with the "fusion" Qt theme (tested with "gtk" and "adwaita" as well):
One caveat: I can't test how it looks in HiDPI conditions, but I hope that dropping fixed width would only improve its behaviour.
edit: Actually, the patch reduces also the minimum height, which looked excessive too.
=> [Qt] Reduce the minimum width of the selection widget

avidemux/qt4/i18n/avidemux_de.ts, avidemux/qt4/i18n/avidemux_ru.ts
After the recent update of the Russian translation a month ago, some obvious omissions from that update still remain uncorrected, so I hope that this is not too inappropriate to address the most visible one
myself. The translation for "Track 1" was missing, causing misalignment, and the literal translation of "Enabled" as "Включено" (neuter) didn't match the gender of the translation for "Track" as "Дорожка" (feminine).
Using this opportunity, I would like to add keyboard accelerators in the German and in the Russian translation of the audio track selection dialog and to fix a single, broken keyboard accelerator in the German translation of the x265 configuration dialog.
=> [i18n/de/ru] Add kb accels to the audio track dialog, add a missing translation and fix agreement in i18n/ru

avidemux/qt4/ADM_UIs/include/DIA_flyDialogQt4.h, avidemux/qt4/ADM_UIs/src/DIA_flyDialog.cpp
This patch should fix wrong scaling by setting maximum value for the slider straight away in the constructor and make the slider approximately reflect the current position, albeit not during playback. It also adds missing tooltips to the navigation buttons.
There is a not yet understood disagreement between the slider value from `sliderGet` immediately after drag and after `nextImage`, the slider jumps slightly backwards.
The total duration accessed as `_in->getInfo()->totalDuration` is not updated if the changeFps filter is added. This might be an issue with underlying code and not the preview dialog's fault.
=> [flyDialog] Fix navigation slider (WIP), add missing tooltips

avidemux/common/gui_main.cpp
My earlier naive attempt to preserve audio codec at least for the first track across videos has only led to a disagreement between the codec widget in the main window and the audio tracks menu as noticed by users: [ 	
Encodage audio non sollicité mais automatique](http://avidemux.org/smif/index.php/topic,17401.0.html), [Audio options not remembered in 2.6.17-18](http://avidemux.org/smif/index.php/topic,17412.0.html). This quick and dirty patch fixes the disagreement, really restoring the previously selected audio codec for the first audio track.
The audio codec reverts to "copy" upon loading a new video if "load default settings" is checked.
=> [UI] Preserve audio codec upon loading a video, now for real

avidemux/qt4/ADM_UIs/src/DIA_flyDialog.cpp
Maybe I'm missing something, but the time display (`labelTime`) added in [[flyDialog] more accurate timestamps + display pts](https://github.com/mean00/avidemux2/commit/c43557270c29704b68721b7747327ade5bf8770e) doesn't get updated in the most cases when navigating in a filter preview because `nextImage()` gets called only when clicking the "Next" button. I guess setting the text of the label belongs into `nextImageInternal()`.
Currently, adding time display to flyDialog results in duplicated time display in the seekable preview, where the new time display looks a bit out of place.
=> [flyDialog] Fix time display

avidemux_plugins/ADM_videoFilters6/resampleFps/ADM_vidResampleFPS.cpp
The `goToTime` function in the "resampleFps" plugin needs the already known [treatment](https://github.com/mean00/avidemux2/commit/2b6dd157d4fef93ad65e4948401401cdbdfcead0) (all credit for the fix goes to Mean, of course).
=> [resampleFps] Apply the same logic as in changeFps to fix goToTime

avidemux/qt4/ADM_userInterfaces/ADM_filters/Q_seekablePreview.cpp, avidemux/qt4/ADM_userInterfaces/ADM_filters/Q_seekablePreview.h
Obviously, we could use the label in the seekable preview currently duplicating the new functionality of the flyDialog to display the total duration of the filtered video instead.
=> [seekablePreview] Show the total duration instead of the current PTS

avidemux_plugins/ADM_videoFilters6/contrast/qt4/Q_contrast.cpp, avidemux_plugins/ADM_videoFilters6/contrast/qt4/Q_contrast.h
As shown in Jan's video in his [Spoiler alert](http://avidemux.org/smif/index.php/topic,17370.0.html) post, the transition between two and three digits for the contrast percentage or positive and negative values for brightness shifts other widgets in the contrast dialog if the font size is large enough for the labels to exceed the default width of the dials (100px). Avoid this by specifying for each label a minimum width derived from the longest string this label can contain.
On this occasion, make the labels translatable.
=> [Qt/contrast] Make dial titles translatable, avoid shifting widgets when turning dials

avidemux/qt4/ADM_UIs/src/DIA_flyDialog.cpp
Replacing `nextImageInternal()` in `ADM_flyDialog::timeout` by `nextImage()` which updates the slider position is everything it needs to make the slider move during playback. The call to `updateSlider()` in `ADM_flyDialog::play` was my mistake and should be removed.
=> [flyDialog] Update slider position during playback

avidemux_plugins/ADM_audioDecoders/ADM_ad_faad/ADM_ad_faad.cpp
This is what the extradata dump in `ADM_faad::initFaad` currently looks like:
```
[initFaad] 13:00:39-651  [FAAD] using 16 bytes of extradata
[initFaad] 13:00:39-651  12   [initFaad] 13:00:39-651  10   [initFaad] 13:00:39-651  00   [initFaad] 13:00:39-651  00   [initFaad] 13:00:39-651  00   [initFaad] 13:00:39-651  00   [initFaad] 13:00:39-651  00   [initFaad] 13:00:39-651  00   [initFaad] 13:00:39-651  00   [initFaad] 13:00:39-651  00   [initFaad] 13:00:39-651  00   [initFaad] 13:00:39-651  00   [initFaad] 13:00:39-651  00   [initFaad] 13:00:39-651  00   [initFaad] 13:00:39-651  00   [initFaad] 13:00:39-651  00   [initFaad] 13:00:39-651  
```
...which is not very legible. With this primitive patch applied:
```
[initFaad] 15:19:16-362  [FAAD] using 16 bytes of extradata
12 10 00 00 00 00 …
```
=> [faad][cosmetics] Improve debug output legibility

avidemux/qt4/i18n/avidemux_ru.ts
This patch addresses a few issues mentioned in [https://github.com/mean00/avidemux2/pull/84](https://github.com/mean00/avidemux2/pull/84) (mainly correcting the usage of the word "граница" as translation for "border" as agreed with the translator), removes a ton of missed leftovers caused by the broken lrelease heuristic (they all originate from the time prior to the [fix](https://github.com/mean00/avidemux2/commit/53f744224a843f12c8ecaabdeaa1b9f494de97d6)) and adds a few keyboard accelerators.
Please note that adding the "hue" filter crashes Avidemux without a usable backtrace when `LANG` is set to `ru_RU.UTF-8` at least on Linux. This crash doesn't happen e.g. with the English or German locale. Deleting `avidemux_ru.qm` helps. The first bad commit seems to be [Updated Russian …
=> [i18n/ru] Correct a few translation, add kbd accels, remove a lot of broken lrelease heuristic leftovers

avidemux_plugins/ADM_videoFilters6/asharp/DIA_flyAsharp.cpp, avidemux_plugins/ADM_videoFilters6/hue/qt4/DIA_flyHue.cpp, avidemux_plugins/ADM_videoFilters6/mSharpen/qt4/DIA_flymsharpen.cpp
Just for convenience, partially reverts [[i18n] Make more strings translatable (Daniel Amm)](https://github.com/mean00/avidemux2/commit/3972605aa5777d95afc5fce035fc47bfb030b6a2) and adds comments based on [https://github.com/mean00/avidemux2/pull/86#issuecomment-277539015](https://github.com/mean00/avidemux2/pull/86#issuecomment-277539015), in case a rewrite of `printString` is not on the immediate agenda.
=> [i18n] Don't translate strings passed to printString, the latter is ASCII-only

avidemux/qt4/ADM_userInterfaces/ADM_gui/file_qt4.cpp, avidemux_core/ADM_coreUtils/include/ADM_last.h, avidemux_core/ADM_coreUtils/src/ADM_last.cpp
The currently existing implementation uses the name of the last file opened via file picker to build the suggested base name of the output video. This is not desirable because a video may be loaded via the "Recent" menu instead.
The patch removes also a forgotten unused leftover of [[qt4] Provide a default filename when saving](https://github.com/mean00/avidemux2/commit/aaf1d9a16e0a1e209f1eb5543c4bdfcb1e9f72c6) and corrects the behaviour if no video has been saved yet and thus `LASTFILES_LASTDIR_WRITE` is empty: in this case `LASTFILES_LASTDIR_READ` is used instead of suggesting an empty string as file name for the output.
Reference: [Naming of saved files](http://avidemux.org/smif/index.php/topic,17304.0.html)
=> [core, qt] Use the base name of the currently loaded video as the default base name when saving

avidemux/common/ADM_videoCodec/src/ADM_ffmpeg_vdpau.cpp
`vdpauGetFormat` accepts WMV3 as supported by hardware (vdpauinfo doesn't list WMV3 as supported, but mpv claims decoding .wmv videos via VDPAU and plays them perfectly), but `decoderFFVDPAU` knows nothing about that resulting in a crash.
It is worth noting that WMV is almost completely broken and unusable in Avidemux, no matter which decoder.
=> [vdpau] Don't crash with WMV3 videos

avidemux/common/ADM_commonUI/GUI_ui.h, avidemux/common/ADM_render/GUI_render.h, avidemux/common/gui_main.cpp, avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2.cpp, avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2.h, avidemux/qt4/ADM_userInterfaces/ADM_gui/T_preview.cpp
If a new video was loaded or the zoom was changed while the Avidemux window was maximized, unmaximizing the window would restore its size prior to entering the maximized state regardless the actual dimensions of the video. This patch implements automatic resizing in this case.
=> [UI] Resize the main window on unmaximizing

avidemux/common/ADM_editor/src/ADM_edit.cpp, avidemux_core/ADM_coreUtils/src/ADM_infoExtractorH264.cpp, avidemux_core/ADM_coreUtils/src/avidemutils.cpp, avidemux_plugins/ADM_audioDecoders/ADM_ad_lav/ADM_ad_lav.cpp, avidemux_plugins/ADM_audioDecoders/ADM_ad_vorbis/ADM_ad_vorbis.cpp, avidemux_plugins/ADM_demuxers/Matroska/ADM_mkvEntries.cpp, avidemux_plugins/ADM_demuxers/Mp4/ADM_mp4Analyzer.cpp, avidemux_plugins/ADM_demuxers/MpegTS/ADM_tsAudio.cpp, avidemux_plugins/ADM_demuxers/OpenDml/ADM_openDML.cpp, avidemux_plugins/ADM_muxers/muxerMp4v2/muxerMp4v2Video.cpp
Since `ADM_info` and `ADM_warning` print timestamps, the result of a lot of workarounds for missing newline at the end of `mixDump` output where `ADM_info("\n");` is used instead looks very wrong. This patch adds the final newline to `mixDump` itself and removes all active (not commented out and not hidden in leftovers like *.orig files in `avidemux_plugins/ADM_demuxers/Mp4` directory) workarounds across the tree.
=> [mixDump] Print a newline at the end, remove workarounds all over the tree

avidemux2.appdata.xml
AppData is a standard to describe GUI applications. In particular, it allows these applications to be searched for and installed through software centers on Fedora, Ubuntu, etc.
This commit embeds a `.appdata.xml` file for Avidemux, so my grandmother can install it without having to open a terminal.
For further information on AppData see:
https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps
Related to: https://github.com/rpmfusion/avidemux/pull/6
=> [desktop integration] Add AppData file

avidemux_plugins/ADM_videoFilters6/mplayerDelogo/qt5/DIA_flyMpDelogo.cpp, avidemux_plugins/ADM_videoFilters6/mplayerDelogo/qt5/DIA_flyMpDelogo.h
This patch fixes in a quick and dirty way the current odd interaction between the spinners and the rubber band. It also reimplements `autoZoom` so that toggling autozoom doesn't change values anymore.
=> [delogo] Fix interaction between the rubber band, the spinners and the zoom (quick and dirty style)

avidemux/common/ADM_videoCodec/src/ADM_ffmpeg_vdpau.cpp
This is a trivial fix for mpeg2 decoding via VDPAU not working after [[vdpau] Probe hw capabilities (experimental)](https://github.com/mean00/avidemux2/commit/868f24f0e70e6b8a559c467407af145eb23eb1bc).
=> [vdpau] Fix detection of support for MPEG-2

avidemux/cli/ADM_userInterfaces/ADM_gui2/gui_none.cpp, avidemux/common/ADM_render/GUI_render.h, avidemux/common/gui_main.cpp, avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2.cpp, avidemux/qt4/ADM_userInterfaces/ADM_gui/T_preview.cpp
This patch replaces a global variable introduced in [[UI] Resize the main window on unmaximizing](https://github.com/mean00/avidemux2/commit/c2c994ca706d1bf35552e4736e2e8d074eb89650) with a setter function.
=> [UI] Resize on unmaximize, slightly less ugly

avidemux/common/ADM_render/GUI_vdpauRender.cpp
VDPAU won't initialize with width and height equal zero, spitting error messages in red into the terminal every time a video is closed. Don't try it in the first place.
=> [render] Avoid trying to use VDPAU render with zero size dimensions

avidemux/qt4/ADM_userInterfaces/ADM_gui/T_preview.cpp
This clears leftovers of previously displayed videos on closing, especially bad with the "Qt" video output.
=> [UI] Refresh the main window on closing a video

avidemux/common/ADM_editor/src/ADM_edit.cpp, avidemux/common/ADM_videoCodec/src/ADM_videoCodec.cpp, avidemux_core/ADM_coreVideoCodec/src/ADM_codecSearch.cpp, avidemux_plugins/ADM_demuxers/OpenDml/ADM_openDML.cpp
This is merely a cosmetic change improving legibility of debug output, which suffers from a few missing (or excessive) newlines mostly but not exclusively in connection with usage of `fourcc::print` function.
There are some spots in the (mostly debug) code which rely on `fourcc::print` **not** including a final newline thus preventing a more straightforward approach which would allow to scrap a lot of `printf("\n");` all over the tree.
=> [cosmetics] Add newline after fourcc::print at some locations

avidemux/common/ADM_commonUI/myOwnMenu.h, avidemux/common/gui_action.names, avidemux/common/gui_main.cpp
Once again upon [request](http://avidemux.org/smif/index.php/topic,17465.msg79418.html#msg79418). This patch exposes resetting markers in GUI with Ctrl+Home as keyboard shortcut.
=> [UI] Allow resetting markers from GUI

avidemux/qt4/CMakeLists.txt, avidemux_plugins/CMakeLists.txt, bootStrap.bash
This patch renames Qt related `bootStrap.bash` options with "qt4" in their names where actually "qt" in general was meant. It clarifies also the wording of a few mostly Qt related build messages to avoid confusion.
=> [build][cosmetics] Don't call it qt4 if it may be qt5

avidemux/common/gui_savenew.cpp, avidemux/qt4/ADM_userInterfaces/ADM_dialog/Q_encoding.cpp, avidemux/qt4/ADM_userInterfaces/ADM_dialog/encoding.ui, avidemux_core/ADM_coreUI/include/DIA_encoding.h, avidemux_core/ADM_coreUI/src/DIA_encoding.cpp
This patch falls way short of the goal to use the single instance of the encoding dialog for both the first and the second pass. It just replaces the working dialog with the encoding one for the first pass with related additional tweaks like disabling the "Advanced" tab and making information about remaining time available. The benefit: it is now possible to minimize Avidemux to the notification area during the first pass too (see [reference](http://avidemux.org/smif/index.php/topic,12493.0.html)). Without re-use of the dialog instance, the application window will pop up after the first pass though.
The patch makes also the "Pass 1" translatable and hides the disfunctional shutdown checkbox and priority  combo – on Linux and Mac completely, on Windows only for the first pass. The name of …
=> [encoding] Use encoding dialog for the first pass (no re-use yet)

avidemux_core/ADM_core/src/ADM_crashdump_mingw.cpp, avidemux_core/ADM_core/src/ADM_crashdump_unix.cpp, avidemux_core/ADM_core/src/ADM_debug.cpp
I crashed Avidemux too often to further ignore this merely cosmetical omission in the output of `ADM_backTrack` for Linux and MinGW (the Apple version of the function has its trailing newline).
=> [crashdump] Add missing newline after file name

avidemux/common/gui_savenew.cpp, avidemux_core/ADM_coreMuxer/include/ADM_muxer.h, avidemux_core/ADM_coreMuxer/src/ADM_muxerUtils.cpp
This patch circumvents difficulties of sharing the encoding dialog between different parts of the application by managing it solely from the core muxer and also cleans up a few includes.
Now it is possible to send Avidemux during the first pass to tray and it will stay there until the second pass is completed.
=> [encoding] Move pass 1 encoding dialog to muxer, reuse it for pass 2

avidemux/common/ADM_editor/include/ADM_edit.hxx, avidemux/common/ADM_editor/include/ADM_segment.h, avidemux/common/ADM_editor/src/ADM_edit.cpp, avidemux/common/ADM_editor/src/ADM_segment.cpp, avidemux/common/ADM_editor/src/utils/ADM_edUndoQueue.cpp, avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2.cpp, avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2.h
This patch cleans up the undo queue a bit, getting rid of global variables and providing necessary helper functions used to determine whether a particular menu item should be enabled or disabled. Disabling e.g. the items in the "Auto" menu avoids Avidemux crashing when selecting any of the items without a video loaded.
Disabling the "Save as Image" submenu instead of the submenu actions is clumsy, but I haven't found a solution for that during the time available.
=> [UI] Enable or disable menu items dynamically

avidemux/common/ADM_editor/src/ADM_segment.cpp, avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2.cpp, avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2.h
This patch fixes `setMenuItemsEnabledState()` not run after loading a video via drag'n'drop and thus not enabling relevant menu items and implements an ugly (but working) hack to disable menu items not usable while playing a video. I think, the nature of the difficulty is explained in the comment in `avidemux/gtk/ADM_userInterfaces/ADM_gui2/GUI_bindings.cpp:254`, but I don't have an idea how to implement a similar solution ATM.
=> [UI] Disable menu items during playback, fix menus disabled after drag-n-drop

avidemux/common/gui_main.cpp
Despite the "connect to avsproxy" menu item getting disabled during playback if [https://github.com/mean00/avidemux2/pull/110](https://github.com/mean00/avidemux2/pull/110) gets merged, this is probably not wrong to additionally safeguard against the crash when trying to connect to avsproxy while playing.
=> [GUI_avsProxy] Return when called during playback, avoid crash

avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2GL.cpp
That small black square of the dummy GL widget at the left top corner of the vumeter looks out of place. It seems like it could be hidden without adverse effects once the probing of OpenGL capabilities has been completed.
=> [polish] Hide the dummy VuMeter OpenGL widget after probing

avidemux/common/gui_main.cpp, avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2.cpp
This patch fixes enabling menus on video load universally, hooking `setMenuItemsEnabledState()` through `UI_updateRecentMenu()` and reversing the order of calls in `A_openVideo` for that purpose. The patch obsoletes and reverts also the part of the previous patch dedicated to the issue with drag'n'drop (which placed the call at a wrong place, by the way – the right one would have been in the body of `MainWindow::openFiles` if the test for `avifileinfo` fails)
=> [UI] Fix menus not enabled if video was loaded on command line

avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2.cpp, avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2_menu.cpp
This patch fixes hopefully all the regressions resulting from the recent beautification and simplification of the `MainWindow::setMenuItemsEnabledState` haystack along with some cosmetic whitespace changes and a couple of comments clarifying my own misleading wording ;-)
=> [Qt] Fix regressions concerning menu items enabling and disabling

avidemux/cli/ADM_userInterfaces/ADM_gui2/gui_none.cpp, avidemux/common/ADM_commonUI/GUI_ui.h, avidemux/common/gui_main.cpp, avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2.cpp, avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2.h, avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2_menu.cpp
This patch implements updating the tunable action shortcuts (just these) at runtime, removing the earlier requirement to restart Avidemux for the changes to take effect.
It moves also a little bit of the menu items enabling and disabling code around, which might be helpful if we need to rebuild menus at runtime later, requiring the action lists to be recreated.
=> [UI] Update shortcuts at runtime, bundle populating of action lists in a separate function

avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2.cpp, avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2.h
This patch implements enabling and disabling buttons in the navigation and selection widgets similar to menu items depending on playback state and loaded video.
=> [Qt] Enable and disable navigation buttons dynamically

avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2.cpp, avidemux/qt4/ADM_userInterfaces/ADM_gui/gui2.ui, avidemux/qt4/ADM_userInterfaces/ADM_gui/translation_table.h
This patch replaces the `player_play.png` icon on the play button with `player_stop.png` on playback, which allows to remove the somewhat redundant dedicated stop button. It doesn't replace the icon in the "Go" menu yet, this could be done in a followup patch.
=> [Qt] Swap the play button icon on playback, remove the dedicated stop button

avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2.cpp
For the sake of consistency, this is the "Go" menu part of play/stop icon swapping which I failed to include into the previous commit. My apologies for the trouble.
=> [Qt] Swap the icon for play/stop on playback in the Go menu too

avidemux/common/ADM_commonUI/myOwnMenu.h
Currently, we use for the items "Previous Frame" and "Next Frame" of the "Go" menu icons from a different icon set with different style and color. Restore consistency.
=> [polish] Use the same icons in the 'Go' menu as in the navigation widget

avidemux/cli/ADM_userInterfaces/ADM_gui2/gui_none.cpp, avidemux/common/ADM_commonUI/GUI_ui.h, avidemux/common/gui_main.cpp, avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2.cpp, avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2.h, avidemux_core/ADM_coreAudioDevice/include/ADM_audiodevice.h, avidemux_core/ADM_coreAudioDevice/include/audio_out.h, avidemux_core/ADM_coreAudioDevice/src/ADM_audiodevice.cpp, avidemux_plugins/ADM_audioDevices/PulseAudioSimple/ADM_devicePulseSimple.h
On Linux, we default to PulseAudioSimple output, which doesn't support volume control. Showing users a non-operational volume slider may be confusing, hide the volume widget if PulseAudioSimple is selected.
Furthermore, reinterpret `UI_updateActionShortcut` as the general way to perform actions on saving preferences, rename in to `UI_applySettings`.
=> [UI/Qt] Hide non-functional volume widget with PulseAudioSimple

avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2.cpp
This patch addresses [the following bugreport](http://avidemux.org/smif/index.php/topic,17465.msg79835.html#msg79835) by acritum.
The reason the issue is solved in Qt GUI instead of in the common Avidemux code is that managing `lastdir_read` in a centralised way in `A_openVideo` or in `A_appendVideo` while looking much more logical would result in an IMHO problematic behaviour when keeping project files and source videos in different locations: instead of opening the most recently used folder with project files, the file selection dialog would always open the folder with the last source video loaded or appended.
Loading a video via command line or ShellExecute won't update `lastdir_read`.
=> [Qt] Set lastdir_read on drag'n'drop as well

avidemux/qt4/ADM_userInterfaces/ADM_gui/gui2.ui
The context menus of the menubar and the toolbar duplicate the functionality of the "View" --> "Toolbars" menu, look a bit strange with nameless entries and are not translatable. This patch disables them for good.
=> [Qt] Disable context menus for menubar and toolbar

avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2.cpp, avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2_menu.cpp
This is hopefully the last bit of the menu items' disabling/enabling work.
=> [Qt] Disable items of the menu 'Recent' submenus on playback

avidemux_plugins/ADM_audioEncoders/lavcodec/ADM_lav_aac.cpp, avidemux_plugins/ADM_audioEncoders/lavcodec/ADM_lav_ac3.cpp, avidemux_plugins/ADM_audioEncoders/lavcodec/ADM_lav_dts.cpp, avidemux_plugins/ADM_audioEncoders/lavcodec/ADM_lav_mp2.cpp, avidemux_plugins/ADM_audioEncoders/lavcodec/audioencoder_lavcodec.cpp
Currently, the configuration dialog suggests illegal max. bitrate of 448kbps for the mp2 lavc encoder, which gets later rejected by FFmpeg. At the same time, users [want](http://avidemux.org/smif/index.php/topic,8505.msg79921.html) to be able to use an ac3 bitrate exceeding the max. bitrate allowed by the DVD spec. Disentangle both at least at the GUI level for now.
=> [ae_lavc] Fix max bitrate for mp2 and ac3

avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2.cpp
All the items of the "Help" menu stayed greyed out after playback had been stopped. The patch fixes this important omission and makes some cosmetical changes, sorting the `MainWindow::buildActionLists()` function logically on this occasion.
=> [GUI] Reenable help menu items after playback

avidemux/common/gui_main.cpp
One more last-minute fix, hopefully completely harmless. The reference: ["Audio Output" number of tracks (not) updating ](http://avidemux.org/smif/index.php/topic,17053.0.html).
=> [UI] Update the number of active audio tracks when running a script

avidemux/qt4/ADM_userInterfaces/ADM_dialog/Q_encoding.cpp
Please let us hide the shutdown checkbox in the encoding dialog on all platforms for now. It doesn't work and just confuses users.
=> [Qt/encoding] Hide the shutdown checkbox on all platforms for now

avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2.cpp
I've missed one more big thing: the tooltips for the one minute backward and forward buttons must be set dynamically too because their respective shortcuts are swappable. This means, I'll have to regenerate translation files once again (I'll try to catch a few fleas like the NVENC h264 config dialog title before I do that).
=> [GUI] Set tooltips for 1min backward/forward buttons dynamically

avidemux_plugins/ADM_videoEncoder/ffNvEnc/ADM_ffNvEnc.cpp
I whish I had noticed this prior to regenerating translation files, but it would be better to fix the copy&paste leftover in the upcoming release anyway.
=> [plugins/NVENC] Fix H.264 encoder configuration dialog title

avidemux/qt4/i18n/avidemux_ca.ts, avidemux/qt4/i18n/avidemux_cs.ts, avidemux/qt4/i18n/avidemux_da.ts, avidemux/qt4/i18n/avidemux_de.ts, avidemux/qt4/i18n/avidemux_el.ts, avidemux/qt4/i18n/avidemux_en.ts, avidemux/qt4/i18n/avidemux_es.ts, avidemux/qt4/i18n/avidemux_eu.ts, avidemux/qt4/i18n/avidemux_fr.ts, avidemux/qt4/i18n/avidemux_hu.ts, avidemux/qt4/i18n/avidemux_it.ts, avidemux/qt4/i18n/avidemux_ja.ts, avidemux/qt4/i18n/avidemux_pl.ts, avidemux/qt4/i18n/avidemux_pt_BR.ts, avidemux/qt4/i18n/avidemux_ru.ts, avidemux/qt4/i18n/avidemux_sr.ts, avidemux/qt4/i18n/avidemux_sr@latin.ts, avidemux/qt4/i18n/avidemux_tr.ts, avidemux/qt4/i18n/avidemux_zh_TW.ts
The few fixes for i18n/fr primarily restore the translation of the navigation buttons' tooltips and the "Video Decoder" label. The patch provides also German and Russian translations for recently added preferences concerning keyboard shortcuts and fixes a couple of other bits in the German translation.
=> [i18n] Regenerate .ts files again, add a few DE and RU translations, fix some translations broken by recent changes in FR and DA

avidemux/qt4/qt4PackageDebian.cmake, avidemux_core/corePackageDebian.cmake, createDebFromSourceUbuntu.bash
`libpng12-0`, declared as build and runtime dependency, is not available anymore on Ubuntu 16.10 and the upcoming 17.04. This patch fixes the `createDebFromSourceUbuntu.bash` script and the installation of the created debs.
Please note that all OpenGL filters broken on Fedora 24 and later are equally broken on Ubuntu 16.10.
=> [build] Fix deb creation on Ubuntu 16.10, add alsa and xvid to deps in the simple build script

avidemux_plugins/ADM_videoDecoder/vpx/ADM_vpx.cpp, avidemux_plugins/ADM_videoDecoder/vpx/vpxPlugin.cpp
This patch fixes swapped UV when decoding VP8 videos using the vpx plugin along with a cosmetical change correcting the decoder name in the menu.
Alternatively, the build of the vpx decoder in the plugins could be disabled as the internal ffmpeg decodes VP8 videos just fine.
Unsure if this is a trivial change, thus going the way of a pull request.
=> [plugins/vpx] Fix swapped UV, menu name

avidemux_plugins/ADM_videoDecoder/vpx/ADM_vpx.cpp, avidemux_plugins/ADM_videoDecoder/vpx/vpxPlugin.cpp
While I still have no idea why VP9 decoding via the internal FFmpeg fails, it works nicely via the vpx plugin with minimal changes in the code. This patch adds VP9 decoding support, the plugin claims the VP9 FCC now.
=> [plugins/vpx] Add VP9 decoding support

avidemux_core/ADM_coreMuxer/src/ADM_coreMuxerFfmpeg.cpp, avidemux_plugins/ADM_muxers/muxerFlv/muxerFlv.cpp, avidemux_plugins/ADM_muxers/muxerMkv/muxerMkv.cpp, avidemux_plugins/ADM_muxers/muxerMp4/muxerMP4.cpp, avidemux_plugins/ADM_muxers/muxerWebm/muxerWebm.cpp, avidemux_plugins/ADM_muxers/muxerffPS/muxerffPS.cpp, avidemux_plugins/ADM_muxers/muxerffTS/muxerffTS.cpp
This patch is probably total rubbish, as I don't understand the matter well enough. Of course, it silences the warning [seen by Jan](http://avidemux.org/smif/index.php/topic,17642.0.html); encoding with FFmpeg-based and other encoders as well as saving in copy mode still seems to work fine. Nevertheless, could you have a look, please?
=> [muxer] Populate codecpar, silence lavc deprecated warning

avidemux_plugins/ADM_demuxers/VapourSynth/ADM_vsProxy_cli.cpp, avidemux_plugins/ADM_demuxers/VapourSynth/qt4/vs.ui, avidemux_plugins/ADM_demuxers/VapourSynth/qt4/vsProxy_qt4.cpp
Working in the same way, as the modification done for avisynth proxy
=> Allow to specify which port to use for the connection of vapoursynth proxy

avidemux_plugins/ADM_demuxers/VapourSynth/ADM_vsProxy_cli.cpp
Incremented the port number port twice by accident, so tried to read out the port value from the wrong position
=> Corrected off by one argument extraction

addons/avsfilter/winetmppath.cpp
avsfilter does not work after wine git commit:
f16cf541068831074a6891688d947f0ce32abdd9 (kernel32: GetTempPathW must zero the remaining buffer.)
GetTempPathW receives size in bytes from wine_tmp_path, but it expects size in wchars.
GetTempPathW (wine source dlls/kernel32/path.c) crashes in line:
memset(path + ret, 0, (count - ret) * sizeof(WCHAR));
because of wrong count value.
=> avsfilter bugfix

cmake/cmake_compile_check/cpu_armel_check.cpp, cmake/cmake_compile_check/cpu_x86-64_check.cpp, cmake/cmake_compile_check/cpu_x86_check.cpp
The code defines a function foo returning int, but contains no return.
So the detection fails with "CPU not supported". As new gccs warng abotu
missing return, it causes the detaction to fail. Switch foo to return
void.
=> cmake: fix detection of CPUs

avidemux_plugins/ADM_videoFilters6/changeFps/changeFps.cpp, avidemux_plugins/ADM_videoFilters6/resampleFps/ADM_vidResampleFPS.cpp, cmake/avidemuxVersion.cmake
1. Add support for 240fps sources (such as slow-motion video captures).
2. Change some NTSC frame rate descriptions from "59.93" to "59.94".
=> Add Support for 240fps Sources

avidemux/qt4/xdg_data/org.avidemux.Avidemux.desktop
Currently the Avidemux `.desktop` file doesn't enable Avidemux to open files directly from the file manager. Nor can it be set as the default application for opening a filetype, even the ones it supports.
This is due to the lack of a `%f` placeholder on the `Exec=` line of the `.desktop` file. The placeholder is replaced with the filename of the single file to be opened, and if it's not present, GNOME Shell and possibly other environments won't consider an application as having the _ability_ to directly open files.
(I didn't use the `%F` multi-file placeholder because in my testing, attempting to open multiple files  with Avidemux doesn't work. Any additional files listed on the command line after the first are simply ignored, not appended.)
With this change, Avidemux appears in the 'Open …
=> Enable file opening via .desktop

avidemux_plugins/ADM_videoEncoder/x265/ADM_x265.h, avidemux_plugins/ADM_videoEncoder/x265/ADM_x265Setup.cpp, avidemux_plugins/ADM_videoEncoder/x265/qt4/Q_x265.cpp, avidemux_plugins/ADM_videoEncoder/x265/qt4/x265ConfigDialog.ui, avidemux_plugins/ADM_videoEncoder/x265/x265_settings.conf, avidemux_plugins/ADM_videoEncoder/x265/x265_settings.h, avidemux_plugins/ADM_videoEncoder/x265/x265_settings_desc.cpp, avidemux_plugins/ADM_videoEncoder/x265/x265_settings_json.cpp
Here are a couple options for x265 that seem useful.
I'd like to be able to duplicate at least the slow preset from x265 in the advanced config, so that it's possible to use slow + extra options.  If I want a longer keyframe interval for 60fps content it's necessary to give up some of options that the x265 authors think are useful enough to include in the preset.
=> X265 options

appImage/AppRunBuster, makeAppImageBusterMinimal.sh
1. Because of the patch with sed in deployBusterMinimal.sh, to replace all absolute paths to `/usr` by relative paths `././` and thelike, AppRunBuster has to change directory to `"${HERE}/usr"`, which it indeed does. But then `"$@"` should be run through a loop to replace relative path or filename arguments in it by their `"realpath"`.
2. The new AppImage runtime passes a variable `ARGV0` to AppRun, which is set to the name/path used to execute the AppImage (for example the name of a symbolic link to the actual AppImage file). That way, if a user or his admin makes three symbolic links to the appImage file, let's say as `avidemux`, `avidemux_jobs`, and `avidemux_cli` (with or without versions in the name), the AppRun script can detect the suffix used, and call the corresponding binary.
3. …
=> Allow choice of executable in AppImage

avidemux_plugins/ADM_demuxers/MpegTS/ADM_tsReadIndex.cpp
The ts.idx2 file stores framerate as fps * 1000, instead of a rational
number with an integer number and denominator, which would be much
better.
It must then convert that back into a rational so it can put inside a
fake AVI header.
It does not use a closest rational approximation algorithm but just hard
codes a few different common frame rates.  And the standard ATSC rate of
60000/1001 was not in the list.  So add it.
=> [demuxers/MpegTS] Fix for 60000/1001 framerate

avidemux_plugins/ADM_videoFilters6/crop/ADM_vidCrop.cpp, avidemux_plugins/ADM_videoFilters6/crop/crop.conf, avidemux_plugins/ADM_videoFilters6/crop/crop.h, avidemux_plugins/ADM_videoFilters6/crop/crop_desc.cpp, avidemux_plugins/ADM_videoFilters6/crop/qt5/DIA_flyCrop.cpp, avidemux_plugins/ADM_videoFilters6/crop/qt5/DIA_flyCrop.h, avidemux_plugins/ADM_videoFilters6/crop/qt5/Q_crop.h, avidemux_plugins/ADM_videoFilters6/crop/qt5/crop.ui
Hi!
Added a "Keep aspect ratio" option to the Crop video filter.
When enabled, the aspect ratio of the source can be maintained on the selected crop area, if the rubber-band is dragged by the bottom-right corner. The top-left corner continue to be free dragging,the numeric inputs are unchanged.
(Use-case: recently i had to cut several scenes out of a video, and the areas of interest had different sizes and positions. )
=> Crop filter keep aspect ratio option

avidemux_plugins/ADM_videoFilters6/eq2/qt4/DIA_flyEq2.cpp, avidemux_plugins/ADM_videoFilters6/eq2/qt4/DIA_flyEq2.h, avidemux_plugins/ADM_videoFilters6/eq2/qt4/Q_eq2.cpp, avidemux_plugins/ADM_videoFilters6/eq2/qt4/Q_eq2.h, avidemux_plugins/ADM_videoFilters6/eq2/qt4/eq2.ui
Hi!
I took the luma histogram from the Contrast filter, and hacked into the MPlayer eq2 video filter.
Also added a "Show full preview" checkbox. When selected, the effects are shown on the full area of the preview, otherwise only on the right half (same as before this commit).
=> MPlayer eq2 video filter luma histogram

avidemux_plugins/ADM_videoFilters6/eq2/ADM_vidEq2.cpp, avidemux_plugins/ADM_videoFilters6/eq2/qt4/DIA_flyEq2.cpp
The red and blue gamma sliders operate as them being swapped. It was fine in 2.7.6.
> The meaning of PLANAR_U and PLANAR_V enumerators was unswapped recently in 3d57249 affecting all code matching anything to these enumerators.
=> MPlayer eq2 bugfix (filters for U-V was swapped)

avidemux_plugins/ADM_videoFilters6/asharp/qt4/Q_asharp.cpp, avidemux_plugins/ADM_videoFilters6/asharp/qt4/Q_asharp.h, avidemux_plugins/ADM_videoFilters6/asharp/qt4/asharp.ui
The ranges of the spinboxes were 0 .. 99
According to [http://avisynth.nl/index.php/ASharp]:
>Unsharp masking threshold range is from 0 to 32.
>Adaptive sharpening strength must be between 0 and 16.
>Block adaptive sharpening must be less than 4.
I double checked with the underlying code, i can confirm these ranges apply here too.
Added slider controls for the spinboxes for convenience (they are in sync with the spinboxes).
Changed "Unknown flag" to "High quality block filtering"
=> ASharp valid range of spinboxes fixed, added sliders for convenience

avidemux_plugins/ADM_videoFilters6/mSharpen/ADM_vidMSharpen.cpp, avidemux_plugins/ADM_videoFilters6/mSharpen/msharpen.conf, avidemux_plugins/ADM_videoFilters6/mSharpen/msharpen.h, avidemux_plugins/ADM_videoFilters6/mSharpen/msharpen_desc.cpp, avidemux_plugins/ADM_videoFilters6/mSharpen/msharpen_json.cpp, avidemux_plugins/ADM_videoFilters6/mSharpen/qt4/DIA_flymsharpen.cpp, avidemux_plugins/ADM_videoFilters6/mSharpen/qt4/Q_msharpen.cpp, avidemux_plugins/ADM_videoFilters6/mSharpen/qt4/Q_msharpen.h, avidemux_plugins/ADM_videoFilters6/mSharpen/qt4/msharpen.ui
>There was a bug in the filter, the "invstrength" variable should be binded to "_param.strength", but sometimes it has not been updated.
>Added sliders for convenience (they are in sync with the spinboxes).
>Also added a "Process chroma" option (intense sharpening can cause color artifacts, if applied on chroma).
>I left the "HighQuality" string as is, to not break translations.
>The UI tab order is set.
I hope its okay this way.
=> MSharpen corrected bugfix and improvements (sliders & process chroma option)

avidemux_plugins/ADM_videoFilters6/crop/qt5/DIA_flyCrop.cpp, avidemux_plugins/ADM_videoFilters6/crop/qt5/DIA_flyCrop.h, avidemux_plugins/ADM_videoFilters6/crop/qt5/crop.ui
Reset button behaviour get fixed, when Keep aspect enabled.
Aspect ratio comboBox get "current selection", also this became the default.
=> [crop/qt5] fix reset button behaviour, add "current selection" option for aspect ratio list

avidemux_plugins/ADM_videoFilters6/artCharcoal/qt4/DIA_flyArtCharcoal.cpp, avidemux_plugins/ADM_videoFilters6/artColorEffect/qt4/DIA_flyArtColorEffect.cpp, avidemux_plugins/ADM_videoFilters6/artPixelize/qt4/DIA_flyArtPixelize.cpp, avidemux_plugins/ADM_videoFilters6/artVHS/qt4/DIA_flyArtVHS.cpp, avidemux_plugins/ADM_videoFilters6/artVignette/qt4/DIA_flyArtVignette.cpp, avidemux_plugins/ADM_videoFilters6/colorTemp/qt4/DIA_flyColorTemp.cpp, avidemux_plugins/ADM_videoFilters6/negative/ADM_negative.cpp
[negative]: extend color range if the source is ADM_COL_RANGE_MPEG
Other filters: copy the whole image (incl. infos&flags!) to the output (instead just the planes) in the preview processor.
=> [videoFilters] Quick fixes

avidemux_plugins/ADM_videoFilters6/colorTemp/ADM_vidColorTemp.cpp, avidemux_plugins/ADM_videoFilters6/colorTemp/qt4/colorTemp.ui
Changed "U-V plane angle of attack" label to "Chroma shift angle".
Also modified the algorithm, to better handle the reduced range (16..235) luma.
=> [colorTemp] fix label, fix for limited range

avidemux_core/ADM_coreVideoCodec/include/ADM_codecFFsimple.h, avidemux_core/ADM_coreVideoCodec/src/ADM_codecFFsimple.cpp, avidemux_core/ADM_coreVideoCodec/src/ADM_ffVp9.cpp
Experimental!
The _ADM_ffmp43_ multihreading does not cover VP9 encoded videos.
I can play now 4k60fps VP9 videos buttery smooth with this patch. With single thread it was p.i.t.a.
As far as i know _ADM_codecFFsimple_ / class _decoderFFSimple_ is not used elsewhere, but _ADM_codecFFVP9_  (is this true?).
Im not sure this is the correct way, to enable MT for VP9, but works for now..
=> [ADM_coreVideoCodec] enable VP9 multithreading

avidemux/qt4/ADM_userInterfaces/ADM_filters/Q_mainfilter.cpp, avidemux/qt4/ADM_userInterfaces/ADM_filters/Q_mainfilter.h
Deleting a filter, dont jump to the end of the list, but stay at the same position if possible
Show shortcut keys in context menu
Add shortcuts for Move Up/Down, and Make partial
=> [Video filter manager] improve UX

avidemux_plugins/ADM_videoFilters6/crop/qt5/DIA_flyCrop.cpp
1) Replace green blanking with green alpha blending.
It makes repositioning easier.
It also provides visible guide lines (bug turned out to be a feature :-) ).
2) Prevent dimension jitter on rubber band move.
=> [crop/qt5] improvements

avidemux/qt4/ADM_userInterfaces/ADM_filters/Q_mainfilter.cpp, avidemux_core/ADM_coreVideoFilter/include/ADM_coreVideoFilterFunc.h, avidemux_core/ADM_coreVideoFilter/src/ADM_coreVideoFilterFunc.cpp
Rebuild bridge and recreate filter chain when the user opens the video filter manager, to update timing info from the editor.
Bugfix for:
1) Video filter preview sometimes only show the fraction of the video, and the reported length is shorter too.
2) Video filter preview sometimes reports the original length, altough sections have been already cut out.
=> [coreVideoFilter] Rebuilding bridge on opening filter manager

avidemux/qt4/ADM_UIs/include/DIA_flyDialogQt4.h, avidemux/qt4/ADM_UIs/src/DIA_flyDialog.cpp
Resizing or dragging the rubber band in the Crop filter is sluggish at 1080p and even more above.
Therefore i improved on ADM_flyDialogRgb (ADM_flyDialogRgb used only by Crop and Blacken border):
- YUV->RGB conversion is performed only when necessary (Pts of the current image changed)
- above 720p scaling is ADM_CS_FAST_BILINEAR instead of ADM_CS_BICUBIC
=> [ADM_flyDialogRgb] improve performance

avidemux_plugins/ADM_audioDevices/Alsa/ADM_deviceALSA.cpp, avidemux_plugins/ADM_audioDevices/Alsa/ADM_deviceALSA.h
I have replaced the volume control with hacked soft control (also fixed the indentations).
The original setVolume was a mess:
- always used (at _snd_mixer_attach_) "hw:0", where ADEVICE should have been used
- however a comment ("_MEANX: Cannot use the real name, does not work with dmix_") indicate it may wont work with "dmix" (i can not confirm it, alsa dmix audio output does not work on my system)
- using ADEVICE, the volume control works, but it will change the global (==system-wide) volume, which is unacceptable.
I have also decreased the buffer size (1s -> 100ms), to reduce the lag between volume change action and effect.
=> [Alsa] replace volume control

avidemux_plugins/ADM_videoFilters6/resampleFps/ADM_vidResampleFPS.cpp, avidemux_plugins/ADM_videoFilters6/resampleFps/CMakeLists.txt, avidemux_plugins/ADM_videoFilters6/resampleFps/confResampleFps.conf, avidemux_plugins/ADM_videoFilters6/resampleFps/confResampleFps.h, avidemux_plugins/ADM_videoFilters6/resampleFps/confResampleFps_desc.cpp, avidemux_plugins/ADM_videoFilters6/resampleFps/confResampleFps_json.cpp, avidemux_plugins/ADM_videoFilters6/resampleFps/motin.cpp, avidemux_plugins/ADM_videoFilters6/resampleFps/motin.h
its experimental / far from perfect, it does not handle large motion well...
it is significantly faster than ffmpeg's minterpolate, but quality lacks behind.
however, if there are no large motions (eg. 20fps->60fps, 30fps->60fps) it is better most of the time than the "Blend" interpolation.
so dont try 1..2..5 fps->60fps conversion :)
there is no scene change detection. visible artifacts can occur.
overall, its not bad for a two afternoon job :)
i dont know cmake at all, so it was a little struggle to make CMakeLists.txt work, i hope its okay in the current state.
=> [resampleFps] add motion compensated interpolation option

avidemux_plugins/ADM_videoFilters6/resampleFps/motin.cpp
I wouldnt tought that std::pow is that slow.
With precalculating i get more than 30% fps increase.
=> [motin] speedup by precalculating distance penalties

avidemux/qt4/ADM_UIs/src/DIA_flyDialog.cpp
The bug only occured with HiDPI scaling & lower (<720p) resolutions videos, and only in filters using ADM_flyDialogRgb.
Symptom: filter's preview is garbage (but obviously looks like scaler - buffer dimension mismatch), which is gone once i resize the filter windows just a small amount.
=> [ADM_flyDialog] fix fitCanvasIntoView

avidemux_plugins/ADM_videoFilters6/crop/qt5/DIA_flyCrop.cpp, avidemux_plugins/ADM_videoFilters6/crop/qt5/DIA_flyCrop.h, avidemux_plugins/ADM_videoFilters6/crop/qt5/Q_crop.cpp
-works on darker scenes then before
-allow odd values (opposite pairs must have same parity)
-it can achieve perfect crops (no black borders left)
-changed ButtonRole of the Auto Crop button to ResetRole, so it is now groupped with the Reset button
=> [crop/qt5] fix autocrop

avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2.cpp, avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2.h
When i continuously press left/right key for navigation (for fine cutting this is inevitable), and the decoder cant keep up, there is a congestion in the action queue. Especially using left key, i can experience more than 10 seconds unresponsive time, when it just keeps going back after i have released the key, and goes way over the desired frame.
=> [Q_gui2] filter navigation actions to prevent congestions

avidemux/common/gui_play.cpp
I remember there was issues reported about unresponsive UI during playback (mostly on windoze).
I have tested it by limiting adm to single core and playing demanding content, i saw some delayed (max 1 sec) response to play stop action.
This patch should fix it, but i can not test it on other platform.
=> [gui_play] improve UI responsiveness during playback

avidemux/cli/ADM_userInterfaces/ADM_dialog/DIA_encoding_none.h, avidemux/common/gui_savenew.cpp, avidemux/qt4/ADM_userInterfaces/ADM_dialog/Q_encoding.cpp, avidemux/qt4/ADM_userInterfaces/ADM_dialog/Q_encoding.h, avidemux/qt4/ADM_userInterfaces/ADM_dialog/encoding.ui, avidemux_core/ADM_coreMuxer/include/ADM_muxer.h, avidemux_core/ADM_coreMuxer/src/ADM_muxerUtils.cpp, avidemux_core/ADM_coreUI/include/DIA_encoding.h, avidemux_core/ADM_coreVideoEncoder/include/ADM_encoderConf.h, avidemux_plugins/ADM_muxers/muxerAvi/muxerAvi.cpp, avidemux_plugins/ADM_muxers/muxerDummy/ADM_dummy.cpp, avidemux_plugins/ADM_muxers/muxerFlv/muxerFlv.cpp, avidemux_plugins/ADM_muxers/muxerMkv/muxerMkv.cpp, avidemux_plugins/ADM_muxers/muxerMp4/muxerMP4.cpp, avidemux_plugins/ADM_muxers/muxerMp4v2/muxerMp4v2.cpp, avidemux_plugins/ADM_muxers/muxerRaw/muxerRaw.cpp, avidemux_plugins/ADM_muxers/muxerffPS/muxerffPS.cpp, avidemux_plugins/ADM_muxers/muxerffTS/muxerffTS.cpp
In the Encoding dialog the output filename with full path is shown.
There is a checkboxed option to delete temporary stats files after encoding is done.
If enabled, it will try to delete:
- filename_with_extension.stats
- filename_with_extension.stats.mbtree
- filename_with_extension.stats.cutree
=> [Q_encoding] display output file name, option for delete temporary files

avidemux/common/ADM_commonUI/DIA_HDRConfig.cpp, avidemux/common/gui_main.cpp
use nextPicture()+previousKeyFrame() to flush cache, and display the effect of the new hdr settings on the closest (prev or same) key frame.
=> [hdr] show changes

avidemux/common/ADM_commonUI/myOwnMenu.h, avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2.cpp
-add hidden shortcuts (Back/Forth 1,2,4 sec & 1 min) to the Go menu, let the users know about them
-KEYBOARD_SHORTCUTS_SWAP_UP_DOWN_KEYS was no applied on Back/Forth 1 min shortcut.
=> [GUI] add hidden shortcuts to Go menu; fix swap up/down in case of 1 min jump

avidemux/common/ADM_videoFilter2/src/ADM_videoFilters.cpp
The preview of a last partialized Add logo filter had messed up timing if their parent partial filter range changed.
=> [ADM_videoFilters] bugfix: recreate filter chain if partial filter reconfigured

avidemux/common/gui_main.cpp
accidentaly tried to restore a previous session, while the source file was already deleted. this led to a crash
=> [gui_main] prevent crash when restoring previous session with deleted video

avidemux/common/ADM_editor/src/ADM_segment.cpp
with enabled shared cache it was crashing when trying to load video in
[https://avidemux.org/smif/index.php?msg=92917](https://avidemux.org/smif/index.php?msg=92917)
=> [ADM_segment] fix crash when loading keyframeless/bogus video while shared cache enabled

avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2.cpp
for example event handler fires rapidly if mouse cursor moving over the main window
=> [Q_gui2] event handler only query preference if relevant

avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2.cpp, avidemux/qt4/ADM_userInterfaces/ADM_gui/Q_gui2.h, avidemux/qt4/ADM_userInterfaces/ADM_gui/gui2.ui
user can change themes on the fly (through View/Themes menu):
-Native theme (option not shown if native theme is fusion)
-Light theme (fusion with default colors)
-Dark theme (fusion with dark colors)
saved to QSettings
=> [GUI] add themes

avidemux/common/ADM_audioFilter/src/audiofilter_interface.cpp, avidemux/qt4/ADM_userInterfaces/ADM_dialog/Q_audioTrackClass.h, avidemux/qt4/ADM_userInterfaces/ADM_dialog/Q_audioTracks.cpp, avidemux/qt4/ADM_userInterfaces/ADM_dialog/Q_audioTracks.h, avidemux/qt4/ADM_userInterfaces/ADM_dialog/audioTracks.ui, avidemux_core/ADM_coreAudioFilter/include/audiofilter_conf.h
-show minimum 4 tracks
-show one inactive track (if possible); if activated, extend the list
-button to duplicate codec and filter config of the first track to other tracks
to maintain the dialog size i used
`this->resize(100,100);  // hacky way to set size to minimum-fit`
which works on linux, but don't now if ok elsewhere...
=> [GUI/audioTracks] show up to 32 tracks

avidemux_core/ADM_coreImage/include/ADM_toneMapper.h, avidemux_core/ADM_coreImage/src/ADM_toneMapper.cpp
- 50-60% faster (on 8C16T)
- eliminated RGB2YUV rounding errors with makeshift conversion
- refactor and eliminate duplicate code
=> [hdr/rgb] performance & quality improvements

cmake/FindGitSvn.cmake
When building from the repo, `ADM_SUBVERSION` is partly generated from the first 11 characters of a `git log --format=oneline` output line. This can misparse the revision string if they're allowed to be abbreviated, which can leave them at only 8 or 9 characters. The resulting `ADM_SUBVERSION`, e.g. `221228_abcde0123 (`, will break `printf` calls in the code due to the unmatched open paren.
Adding `--no-abbrev` to the command ensures that the full 40-character SHA  is output, which can then be truncated to whatever length the script needs.
=> CMake: Ensure git rev SHAs aren't abbreviated

avidemux_core/ADM_core/include/ADM_cpuSIMD.h, avidemux_core/ADM_core/include/sse2neon.h, avidemux_plugins/ADM_videoFilters6/aiEnhance/FSRCNN.cpp, avidemux_plugins/ADM_videoFilters6/aiEnhance/NeuronSW.cpp, avidemux_plugins/ADM_videoFilters6/aiEnhance/NeuronSW.h, avidemux_plugins/ADM_videoFilters6/aiEnhance/fastFSRCNN.cpp
core header for SIMD intrinsics
pulling in [https://github.com/DLTcollab/sse2neon](https://github.com/DLTcollab/sse2neon) SIMD translator
compiler arch options needs to be extended with "fp+simd" if not already done (I.D.K.), so smthing like "-march=armv8-a+fp+simd" in case of ADM_CPU_ARM64
can't test it
=> [core] CPU SIMD + sse2neon

bootStrap.bash, bootStrapHaikuOS.bash, bootStrapOsx_Catalina.bash, bootStrapOsx_HighSierra.bash, bootStrapOsx_Sierra.bash
`CMAKE_EDIT_COMMAND` is mean to be an internal variable, used only for implementing the `make edit_cache` target of Makefile Generators. It's supposed to contain the path to a CMake editor like `ccmake` or `cmake-gui`, and will be called with arguments not accepted by `vim`, `mcedit`, or any other generic editor.
Ref: https://cmake.org/cmake/help/latest/variable/CMAKE_EDIT_COMMAND.html
Here's what happens if you run `make edit_cache` with the `CMAKE_EDIT_COMMAND` set to `vim` as in the bootstrap scripts:
```console
$ cd buildCli
$ make edit_cache
Running CMake cache editor...
vim -S.../avidemux2/avidemux/cli -B.../avidemux2/buildCli
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Dec 14 2022 00:00:00)
Garbage after option argument: "-S.../avidemux2/avidemux/cli"
More info with: "vim -h" …
```
=> [cmake] Don't set CMAKE_EDIT_COMMAND

avidemux_core/ffmpeg_package/patches/upstream/libavutil_hwcontext_vulkan.c.patch
Fixes errors compiling ffmpeg5x about vulkan headers: https://trac.ffmpeg.org/ticket/10115
```
libavutil/hwcontext_vulkan.c:367:7: error: 'VK_EXT_VIDEO_DECODE_H264_EXTENSION_NAME' undeclared here (not in a function); did you mean 'VK_EXT_VIDEO_ENCODE_H264_EXTENSION_NAME'?
367 |     { VK_EXT_VIDEO_DECODE_H264_EXTENSION_NAME,                FF_VK_EXT_NO_FLAG                },
|       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|       VK_EXT_VIDEO_ENCODE_H264_EXTENSION_NAME
libavutil/hwcontext_vulkan.c:368:7: error: 'VK_EXT_VIDEO_DECODE_H265_EXTENSION_NAME' undeclared here (not in a function); did you mean 'VK_EXT_VIDEO_ENCODE_H265_EXTENSION_NAME'?
368 |     { VK_EXT_VIDEO_DECODE_H265_EXTENSION_NAME,                FF_VK_EXT_NO_FLAG                },
| …
```
=> [ffmpeg/patches] Add upstream patch to fix ffmpeg5x compilation

avidemux_core/ADM_coreImage/src/ADM_colorspace.cpp
Clang 16 (to be released appx. March 2023) will make the following default errors: -Werror=implicit-function-declaration
-Werror=implicit-int
-Werror=int-conversion (this is in Clang 15, actually) -Werror=incompatible-function-pointer-types (GCC does not have a specific equivalent error, use -Werror=incompatible-pointer-types instead when testing)
Building with Clang-16 results in build failure with non-constant-expression cannot be narrowed from type 'uint32_t' error with clang-16. Following what the compiler suggests, adding a static_cast<int> helps suppress the error.
=> Fix building with clang 16

avidemux_plugins/ADM_demuxers/Mp4/ADM_mp4.cpp, avidemux_plugins/ADM_demuxers/Mp4/ADM_mp4.h, avidemux_plugins/ADM_demuxers/Mp4/ADM_mp4Indexer.cpp
only saves frame flags, to skip the long "Decoding frame type" process
if "Decoding frame type" not triggered, then index is not created, bc. the file already opens quickly
=> [ADM_demuxers/Mp4] index to file option
